"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.exceptions.api_exception import (
    ApiException,
)
from restapi.models.listen_v_1_response_metadata import (
    ListenV1ResponseMetadata,
)
from restapi.models.listen_v_1_response_results import (
    ListenV1ResponseResults,
)


class ListenV1ResponseErrorException(ApiException):
    def __init__(self, reason, response):
        """Initialize ListenV1ResponseErrorException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(ListenV1ResponseErrorException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.metadata =\
            ListenV1ResponseMetadata.from_dictionary(
                dictionary.get("metadata"))\
                if dictionary.get("metadata") else None
        self.results =\
            ListenV1ResponseResults.from_dictionary(
                dictionary.get("results"))\
                if dictionary.get("results") else None


    def __str__(self):
        """Return a human-readable string representation."""
        _metadata=self.metadata
        _results=self.results
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"metadata={_metadata!s}, "
            f"results={_results!s}, "
            f")"
        )
