"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class AgentThinkModelsV1ResponseModelsItemsOneOf0Id(object):
    """Implementation of the 'AgentThinkModelsV1ResponseModelsItemsOneOf0Id' enum.

    The unique identifier of the OpenAI model

    Attributes:
        GPT5: The enum member of type str.
        GPT5MINI: The enum member of type str.
        GPT5NANO: The enum member of type str.
        ENUM_GPT41: The enum member of type str.
        ENUM_GPT41MINI: The enum member of type str.
        ENUM_GPT41NANO: The enum member of type str.
        GPT4O: The enum member of type str.
        GPT4OMINI: The enum member of type str.

    """

    _all_values = ["gpt-5", "gpt-5-mini", "gpt-5-nano", "gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano",
        "gpt-4o", "gpt-4o-mini"]
    GPT5 = "gpt-5"

    GPT5MINI = "gpt-5-mini"

    GPT5NANO = "gpt-5-nano"

    ENUM_GPT41 = "gpt-4.1"

    ENUM_GPT41MINI = "gpt-4.1-mini"

    ENUM_GPT41NANO = "gpt-4.1-nano"

    GPT4O = "gpt-4o"

    GPT4OMINI = "gpt-4o-mini"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
