"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper


class GetModelV1Response0(object):
    """Implementation of the 'GetModelV1Response0' model.

    Attributes:
        name (str): The model property of type str.
        canonical_name (str): The model property of type str.
        architecture (str): The model property of type str.
        languages (List[str]): The model property of type List[str].
        version (str): The model property of type str.
        uuid (uuid|str): The model property of type uuid|str.
        batch (bool): The model property of type bool.
        streaming (bool): The model property of type bool.
        formatted_output (bool): The model property of type bool.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "canonical_name": "canonical_name",
        "architecture": "architecture",
        "languages": "languages",
        "version": "version",
        "uuid": "uuid",
        "batch": "batch",
        "streaming": "streaming",
        "formatted_output": "formatted_output",
    }

    _optionals = [
        "name",
        "canonical_name",
        "architecture",
        "languages",
        "version",
        "uuid",
        "batch",
        "streaming",
        "formatted_output",
    ]

    def __init__(
        self,
        name=APIHelper.SKIP,
        canonical_name=APIHelper.SKIP,
        architecture=APIHelper.SKIP,
        languages=APIHelper.SKIP,
        version=APIHelper.SKIP,
        uuid=APIHelper.SKIP,
        batch=APIHelper.SKIP,
        streaming=APIHelper.SKIP,
        formatted_output=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GetModelV1Response0 instance."""
        # Initialize members of the class
        if name is not APIHelper.SKIP:
            self.name = name
        if canonical_name is not APIHelper.SKIP:
            self.canonical_name = canonical_name
        if architecture is not APIHelper.SKIP:
            self.architecture = architecture
        if languages is not APIHelper.SKIP:
            self.languages = languages
        if version is not APIHelper.SKIP:
            self.version = version
        if uuid is not APIHelper.SKIP:
            self.uuid = uuid
        if batch is not APIHelper.SKIP:
            self.batch = batch
        if streaming is not APIHelper.SKIP:
            self.streaming = streaming
        if formatted_output is not APIHelper.SKIP:
            self.formatted_output = formatted_output

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        canonical_name =\
            dictionary.get("canonical_name")\
            if dictionary.get("canonical_name")\
                else APIHelper.SKIP
        architecture =\
            dictionary.get("architecture")\
            if dictionary.get("architecture")\
                else APIHelper.SKIP
        languages =\
            dictionary.get("languages")\
            if dictionary.get("languages")\
                else APIHelper.SKIP
        version =\
            dictionary.get("version")\
            if dictionary.get("version")\
                else APIHelper.SKIP
        uuid =\
            dictionary.get("uuid")\
            if dictionary.get("uuid")\
                else APIHelper.SKIP
        batch =\
            dictionary.get("batch")\
            if "batch" in dictionary.keys()\
                else APIHelper.SKIP
        streaming =\
            dictionary.get("streaming")\
            if "streaming" in dictionary.keys()\
                else APIHelper.SKIP
        formatted_output =\
            dictionary.get("formatted_output")\
            if "formatted_output" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   canonical_name,
                   architecture,
                   languages,
                   version,
                   uuid,
                   batch,
                   streaming,
                   formatted_output,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _canonical_name=(
            self.canonical_name
            if hasattr(self, "canonical_name")
            else None
        )
        _architecture=(
            self.architecture
            if hasattr(self, "architecture")
            else None
        )
        _languages=(
            self.languages
            if hasattr(self, "languages")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _uuid=(
            self.uuid
            if hasattr(self, "uuid")
            else None
        )
        _batch=(
            self.batch
            if hasattr(self, "batch")
            else None
        )
        _streaming=(
            self.streaming
            if hasattr(self, "streaming")
            else None
        )
        _formatted_output=(
            self.formatted_output
            if hasattr(self, "formatted_output")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"canonical_name={_canonical_name!r}, "
            f"architecture={_architecture!r}, "
            f"languages={_languages!r}, "
            f"version={_version!r}, "
            f"uuid={_uuid!r}, "
            f"batch={_batch!r}, "
            f"streaming={_streaming!r}, "
            f"formatted_output={_formatted_output!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _canonical_name=(
            self.canonical_name
            if hasattr(self, "canonical_name")
            else None
        )
        _architecture=(
            self.architecture
            if hasattr(self, "architecture")
            else None
        )
        _languages=(
            self.languages
            if hasattr(self, "languages")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _uuid=(
            self.uuid
            if hasattr(self, "uuid")
            else None
        )
        _batch=(
            self.batch
            if hasattr(self, "batch")
            else None
        )
        _streaming=(
            self.streaming
            if hasattr(self, "streaming")
            else None
        )
        _formatted_output=(
            self.formatted_output
            if hasattr(self, "formatted_output")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"canonical_name={_canonical_name!s}, "
            f"architecture={_architecture!s}, "
            f"languages={_languages!s}, "
            f"version={_version!s}, "
            f"uuid={_uuid!s}, "
            f"batch={_batch!s}, "
            f"streaming={_streaming!s}, "
            f"formatted_output={_formatted_output!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
