"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper


class GetProjectDistributionCredentialsV1ResponseMember(object):
    """Implementation of the
    'GetProjectDistributionCredentialsV1ResponseMember' model.

    Attributes:
        member_id (uuid|str): Unique identifier for the member
        email (str): Email address of the member
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "member_id": "member_id",
        "email": "email",
    }

    def __init__(
        self,
        member_id=None,
        email=None,
        additional_properties=None):
        """Initialize a GetProjectDistributionCredentialsV1ResponseMember instance."""
        # Initialize members of the class
        self.member_id = member_id
        self.email = email

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        member_id =\
            dictionary.get("member_id")\
            if dictionary.get("member_id")\
                else None
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(member_id,
                   email,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _member_id=self.member_id
        _email=self.email
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member_id={_member_id!r}, "
            f"email={_email!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _member_id=self.member_id
        _email=self.email
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member_id={_member_id!s}, "
            f"email={_email!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
