"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper


class GrantV1Request(object):
    """Implementation of the 'GrantV1Request' model.

    Attributes:
        ttl_seconds (float): Time to live in seconds for the token. Defaults to 30
            seconds.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ttl_seconds": "ttl_seconds",
    }

    _optionals = [
        "ttl_seconds",
    ]

    def __init__(
        self,
        ttl_seconds=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GrantV1Request instance."""
        # Initialize members of the class
        if ttl_seconds is not APIHelper.SKIP:
            self.ttl_seconds = ttl_seconds

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ttl_seconds =\
            dictionary.get("ttl_seconds")\
            if dictionary.get("ttl_seconds")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(ttl_seconds,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ttl_seconds=(
            self.ttl_seconds
            if hasattr(self, "ttl_seconds")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ttl_seconds={_ttl_seconds!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ttl_seconds=(
            self.ttl_seconds
            if hasattr(self, "ttl_seconds")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ttl_seconds={_ttl_seconds!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
