"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper


class ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentials(object):
    """Implementation of the
    'ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentials' model.

    Attributes:
        distribution_credentials_id (uuid|str): Unique identifier for the
            distribution credentials
        provider (str): The provider of the distribution service
        comment (str): Optional comment about the credentials
        scopes (List[str]): List of permission scopes for the credentials
        created (datetime): Timestamp when the credentials were created
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "distribution_credentials_id": "distribution_credentials_id",
        "provider": "provider",
        "scopes": "scopes",
        "created": "created",
        "comment": "comment",
    }

    _optionals = [
        "comment",
    ]

    def __init__(
        self,
        distribution_credentials_id=None,
        provider=None,
        scopes=None,
        created=None,
        comment=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a
        ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentials instance.
        """
        # Initialize members of the class
        self.distribution_credentials_id = distribution_credentials_id
        self.provider = provider
        if comment is not APIHelper.SKIP:
            self.comment = comment
        self.scopes = scopes
        self.created =\
             APIHelper.apply_datetime_converter(
            created, APIHelper.RFC3339DateTime)\
             if created else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        distribution_credentials_id =\
            dictionary.get("distribution_credentials_id")\
            if dictionary.get("distribution_credentials_id")\
                else None
        provider =\
            dictionary.get("provider")\
            if dictionary.get("provider")\
                else None
        scopes =\
            dictionary.get("scopes")\
            if dictionary.get("scopes")\
                else None
        created = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created")).datetime\
            if dictionary.get("created") else None
        comment =\
            dictionary.get("comment")\
            if dictionary.get("comment")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(distribution_credentials_id,
                   provider,
                   scopes,
                   created,
                   comment,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _distribution_credentials_id=self.distribution_credentials_id
        _provider=self.provider
        _comment=(
            self.comment
            if hasattr(self, "comment")
            else None
        )
        _scopes=self.scopes
        _created=self.created
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"distribution_credentials_id={_distribution_credentials_id!r}, "
            f"provider={_provider!r}, "
            f"comment={_comment!r}, "
            f"scopes={_scopes!r}, "
            f"created={_created!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _distribution_credentials_id=self.distribution_credentials_id
        _provider=self.provider
        _comment=(
            self.comment
            if hasattr(self, "comment")
            else None
        )
        _scopes=self.scopes
        _created=self.created
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"distribution_credentials_id={_distribution_credentials_id!s}, "
            f"provider={_provider!s}, "
            f"comment={_comment!s}, "
            f"scopes={_scopes!s}, "
            f"created={_created!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
