"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper


class ListBillingFieldsV1Response(object):
    """Implementation of the 'ListBillingFieldsV1Response' model.

    Attributes:
        accessors (List[uuid|str]): List of accessor UUIDs for the time period
        deployments (List[ListBillingFieldsV1ResponseDeploymentsItems]): List of
            deployment types for the time period
        tags (List[str]): List of tags for the time period
        line_items (Dict[str, str]): Map of line item names to human-readable
            descriptions for the time period
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "accessors": "accessors",
        "deployments": "deployments",
        "tags": "tags",
        "line_items": "line_items",
    }

    _optionals = [
        "accessors",
        "deployments",
        "tags",
        "line_items",
    ]

    def __init__(
        self,
        accessors=APIHelper.SKIP,
        deployments=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        line_items=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListBillingFieldsV1Response instance."""
        # Initialize members of the class
        if accessors is not APIHelper.SKIP:
            self.accessors = accessors
        if deployments is not APIHelper.SKIP:
            self.deployments = deployments
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if line_items is not APIHelper.SKIP:
            self.line_items = line_items

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        accessors =\
            dictionary.get("accessors")\
            if dictionary.get("accessors")\
                else APIHelper.SKIP
        deployments =\
            dictionary.get("deployments")\
            if dictionary.get("deployments")\
                else APIHelper.SKIP
        tags =\
            dictionary.get("tags")\
            if dictionary.get("tags")\
                else APIHelper.SKIP
        line_items =\
            dictionary.get("line_items")\
            if dictionary.get("line_items")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(accessors,
                   deployments,
                   tags,
                   line_items,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _accessors=(
            self.accessors
            if hasattr(self, "accessors")
            else None
        )
        _deployments=(
            self.deployments
            if hasattr(self, "deployments")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _line_items=(
            self.line_items
            if hasattr(self, "line_items")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"accessors={_accessors!r}, "
            f"deployments={_deployments!r}, "
            f"tags={_tags!r}, "
            f"line_items={_line_items!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _accessors=(
            self.accessors
            if hasattr(self, "accessors")
            else None
        )
        _deployments=(
            self.deployments
            if hasattr(self, "deployments")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _line_items=(
            self.line_items
            if hasattr(self, "line_items")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"accessors={_accessors!s}, "
            f"deployments={_deployments!s}, "
            f"tags={_tags!s}, "
            f"line_items={_line_items!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
