"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper


class ListProjectKeysV1ResponseApiKeysItemsApiKey(object):
    """Implementation of the 'ListProjectKeysV1ResponseApiKeysItemsApiKey' model.

    Attributes:
        api_key_id (str): The model property of type str.
        comment (str): The model property of type str.
        scopes (List[str]): The model property of type List[str].
        created (datetime): The model property of type datetime.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "api_key_id": "api_key_id",
        "comment": "comment",
        "scopes": "scopes",
        "created": "created",
    }

    _optionals = [
        "api_key_id",
        "comment",
        "scopes",
        "created",
    ]

    def __init__(
        self,
        api_key_id=APIHelper.SKIP,
        comment=APIHelper.SKIP,
        scopes=APIHelper.SKIP,
        created=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListProjectKeysV1ResponseApiKeysItemsApiKey instance."""
        # Initialize members of the class
        if api_key_id is not APIHelper.SKIP:
            self.api_key_id = api_key_id
        if comment is not APIHelper.SKIP:
            self.comment = comment
        if scopes is not APIHelper.SKIP:
            self.scopes = scopes
        if created is not APIHelper.SKIP:
            self.created =\
                 APIHelper.apply_datetime_converter(
                created, APIHelper.RFC3339DateTime)\
                 if created else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        api_key_id =\
            dictionary.get("api_key_id")\
            if dictionary.get("api_key_id")\
                else APIHelper.SKIP
        comment =\
            dictionary.get("comment")\
            if dictionary.get("comment")\
                else APIHelper.SKIP
        scopes =\
            dictionary.get("scopes")\
            if dictionary.get("scopes")\
                else APIHelper.SKIP
        created = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created")).datetime\
            if dictionary.get("created") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(api_key_id,
                   comment,
                   scopes,
                   created,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _api_key_id=(
            self.api_key_id
            if hasattr(self, "api_key_id")
            else None
        )
        _comment=(
            self.comment
            if hasattr(self, "comment")
            else None
        )
        _scopes=(
            self.scopes
            if hasattr(self, "scopes")
            else None
        )
        _created=(
            self.created
            if hasattr(self, "created")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"api_key_id={_api_key_id!r}, "
            f"comment={_comment!r}, "
            f"scopes={_scopes!r}, "
            f"created={_created!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _api_key_id=(
            self.api_key_id
            if hasattr(self, "api_key_id")
            else None
        )
        _comment=(
            self.comment
            if hasattr(self, "comment")
            else None
        )
        _scopes=(
            self.scopes
            if hasattr(self, "scopes")
            else None
        )
        _created=(
            self.created
            if hasattr(self, "created")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"api_key_id={_api_key_id!s}, "
            f"comment={_comment!s}, "
            f"scopes={_scopes!s}, "
            f"created={_created!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
