"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper
from deepgram.models.project_request_response import (
    ProjectRequestResponse,
)


class ListProjectRequestsV1Response(object):
    """Implementation of the 'ListProjectRequestsV1Response' model.

    Attributes:
        page (float): The page number of the paginated response
        limit (float): The number of results per page
        requests (List[ProjectRequestResponse]): The model property of type
            List[ProjectRequestResponse].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "page": "page",
        "limit": "limit",
        "requests": "requests",
    }

    _optionals = [
        "page",
        "limit",
        "requests",
    ]

    def __init__(
        self,
        page=APIHelper.SKIP,
        limit=APIHelper.SKIP,
        requests=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListProjectRequestsV1Response instance."""
        # Initialize members of the class
        if page is not APIHelper.SKIP:
            self.page = page
        if limit is not APIHelper.SKIP:
            self.limit = limit
        if requests is not APIHelper.SKIP:
            self.requests = requests

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        page =\
            dictionary.get("page")\
            if dictionary.get("page")\
                else APIHelper.SKIP
        limit =\
            dictionary.get("limit")\
            if dictionary.get("limit")\
                else APIHelper.SKIP
        requests = None
        if dictionary.get("requests") is not None:
            requests = [
                ProjectRequestResponse.from_dictionary(x)
                    for x in dictionary.get("requests")
            ]
        else:
            requests = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(page,
                   limit,
                   requests,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _page=(
            self.page
            if hasattr(self, "page")
            else None
        )
        _limit=(
            self.limit
            if hasattr(self, "limit")
            else None
        )
        _requests=(
            self.requests
            if hasattr(self, "requests")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"page={_page!r}, "
            f"limit={_limit!r}, "
            f"requests={_requests!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _page=(
            self.page
            if hasattr(self, "page")
            else None
        )
        _limit=(
            self.limit
            if hasattr(self, "limit")
            else None
        )
        _requests=(
            self.requests
            if hasattr(self, "requests")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"page={_page!s}, "
            f"limit={_limit!s}, "
            f"requests={_requests!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
