"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper
from deepgram.models.list_project_purchases_v_1_response_orders_items import (
    ListProjectPurchasesV1ResponseOrdersItems,
)


class ListProjectPurchasesV1Response(object):
    """Implementation of the 'ListProjectPurchasesV1Response' model.

    Attributes:
        orders (List[ListProjectPurchasesV1ResponseOrdersItems]): The model property
            of type List[ListProjectPurchasesV1ResponseOrdersItems].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "orders": "orders",
    }

    _optionals = [
        "orders",
    ]

    def __init__(
        self,
        orders=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListProjectPurchasesV1Response instance."""
        # Initialize members of the class
        if orders is not APIHelper.SKIP:
            self.orders = orders

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        orders = None
        if dictionary.get("orders") is not None:
            orders = [
                ListProjectPurchasesV1ResponseOrdersItems.from_dictionary(x)
                    for x in dictionary.get("orders")
            ]
        else:
            orders = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(orders,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _orders=(
            self.orders
            if hasattr(self, "orders")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"orders={_orders!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _orders=(
            self.orders
            if hasattr(self, "orders")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"orders={_orders!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
