"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper
from deepgram.models.agent_variable_v_1 import (
    AgentVariableV1,
)


class ListAgentVariablesV1Response(object):
    """Implementation of the 'ListAgentVariablesV1Response' model.

    Attributes:
        variables (List[AgentVariableV1]): A list of agent variables for the project
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "variables": "variables",
    }

    _optionals = [
        "variables",
    ]

    def __init__(
        self,
        variables=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListAgentVariablesV1Response instance."""
        # Initialize members of the class
        if variables is not APIHelper.SKIP:
            self.variables = variables

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        variables = None
        if dictionary.get("variables") is not None:
            variables = [
                AgentVariableV1.from_dictionary(x)
                    for x in dictionary.get("variables")
            ]
        else:
            variables = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(variables,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _variables=(
            self.variables
            if hasattr(self, "variables")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"variables={_variables!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _variables=(
            self.variables
            if hasattr(self, "variables")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"variables={_variables!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
