"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper
from deepgram.models.list_project_invites_v_1_response_invites_items import (
    ListProjectInvitesV1ResponseInvitesItems,
)


class ListProjectInvitesV1Response(object):
    """Implementation of the 'ListProjectInvitesV1Response' model.

    Attributes:
        invites (List[ListProjectInvitesV1ResponseInvitesItems]): The model property
            of type List[ListProjectInvitesV1ResponseInvitesItems].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "invites": "invites",
    }

    _optionals = [
        "invites",
    ]

    def __init__(
        self,
        invites=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListProjectInvitesV1Response instance."""
        # Initialize members of the class
        if invites is not APIHelper.SKIP:
            self.invites = invites

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        invites = None
        if dictionary.get("invites") is not None:
            invites = [
                ListProjectInvitesV1ResponseInvitesItems.from_dictionary(x)
                    for x in dictionary.get("invites")
            ]
        else:
            invites = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(invites,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _invites=(
            self.invites
            if hasattr(self, "invites")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"invites={_invites!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _invites=(
            self.invites
            if hasattr(self, "invites")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"invites={_invites!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
