"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper


class ProjectRequestResponse(object):
    """Implementation of the 'ProjectRequestResponse' model.

    A single request

    Attributes:
        request_id (str): The unique identifier of the request
        project_uuid (str): The unique identifier of the project
        created (datetime): The date and time the request was created
        path (str): The API path of the request
        api_key_id (str): The unique identifier of the API key
        response (Any): The response of the request
        code (float): The response code of the request
        deployment (str): The deployment type
        callback (str): The callback URL for the request
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "request_id": "request_id",
        "project_uuid": "project_uuid",
        "created": "created",
        "path": "path",
        "api_key_id": "api_key_id",
        "response": "response",
        "code": "code",
        "deployment": "deployment",
        "callback": "callback",
    }

    _optionals = [
        "request_id",
        "project_uuid",
        "created",
        "path",
        "api_key_id",
        "response",
        "code",
        "deployment",
        "callback",
    ]

    def __init__(
        self,
        request_id=APIHelper.SKIP,
        project_uuid=APIHelper.SKIP,
        created=APIHelper.SKIP,
        path=APIHelper.SKIP,
        api_key_id=APIHelper.SKIP,
        response=APIHelper.SKIP,
        code=APIHelper.SKIP,
        deployment=APIHelper.SKIP,
        callback=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ProjectRequestResponse instance."""
        # Initialize members of the class
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id
        if project_uuid is not APIHelper.SKIP:
            self.project_uuid = project_uuid
        if created is not APIHelper.SKIP:
            self.created =\
                 APIHelper.apply_datetime_converter(
                created, APIHelper.RFC3339DateTime)\
                 if created else None
        if path is not APIHelper.SKIP:
            self.path = path
        if api_key_id is not APIHelper.SKIP:
            self.api_key_id = api_key_id
        if response is not APIHelper.SKIP:
            self.response = response
        if code is not APIHelper.SKIP:
            self.code = code
        if deployment is not APIHelper.SKIP:
            self.deployment = deployment
        if callback is not APIHelper.SKIP:
            self.callback = callback

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else APIHelper.SKIP
        project_uuid =\
            dictionary.get("project_uuid")\
            if dictionary.get("project_uuid")\
                else APIHelper.SKIP
        created = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created")).datetime\
            if dictionary.get("created") else APIHelper.SKIP
        path =\
            dictionary.get("path")\
            if dictionary.get("path")\
                else APIHelper.SKIP
        api_key_id =\
            dictionary.get("api_key_id")\
            if dictionary.get("api_key_id")\
                else APIHelper.SKIP
        response =\
            dictionary.get("response")\
            if dictionary.get("response")\
                else APIHelper.SKIP
        code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else APIHelper.SKIP
        deployment =\
            dictionary.get("deployment")\
            if dictionary.get("deployment")\
                else APIHelper.SKIP
        callback =\
            dictionary.get("callback")\
            if dictionary.get("callback")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(request_id,
                   project_uuid,
                   created,
                   path,
                   api_key_id,
                   response,
                   code,
                   deployment,
                   callback,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _project_uuid=(
            self.project_uuid
            if hasattr(self, "project_uuid")
            else None
        )
        _created=(
            self.created
            if hasattr(self, "created")
            else None
        )
        _path=(
            self.path
            if hasattr(self, "path")
            else None
        )
        _api_key_id=(
            self.api_key_id
            if hasattr(self, "api_key_id")
            else None
        )
        _response=(
            self.response
            if hasattr(self, "response")
            else None
        )
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _deployment=(
            self.deployment
            if hasattr(self, "deployment")
            else None
        )
        _callback=(
            self.callback
            if hasattr(self, "callback")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"request_id={_request_id!r}, "
            f"project_uuid={_project_uuid!r}, "
            f"created={_created!r}, "
            f"path={_path!r}, "
            f"api_key_id={_api_key_id!r}, "
            f"response={_response!r}, "
            f"code={_code!r}, "
            f"deployment={_deployment!r}, "
            f"callback={_callback!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _project_uuid=(
            self.project_uuid
            if hasattr(self, "project_uuid")
            else None
        )
        _created=(
            self.created
            if hasattr(self, "created")
            else None
        )
        _path=(
            self.path
            if hasattr(self, "path")
            else None
        )
        _api_key_id=(
            self.api_key_id
            if hasattr(self, "api_key_id")
            else None
        )
        _response=(
            self.response
            if hasattr(self, "response")
            else None
        )
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _deployment=(
            self.deployment
            if hasattr(self, "deployment")
            else None
        )
        _callback=(
            self.callback
            if hasattr(self, "callback")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"request_id={_request_id!s}, "
            f"project_uuid={_project_uuid!s}, "
            f"created={_created!s}, "
            f"path={_path!s}, "
            f"api_key_id={_api_key_id!s}, "
            f"response={_response!s}, "
            f"code={_code!s}, "
            f"deployment={_deployment!s}, "
            f"callback={_callback!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
