"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper


class SharedSentimentsSegmentsItems(object):
    """Implementation of the 'SharedSentimentsSegmentsItems' model.

    Attributes:
        text (str): The model property of type str.
        start_word (float): The model property of type float.
        end_word (float): The model property of type float.
        sentiment (str): The model property of type str.
        sentiment_score (float): The model property of type float.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "text": "text",
        "start_word": "start_word",
        "end_word": "end_word",
        "sentiment": "sentiment",
        "sentiment_score": "sentiment_score",
    }

    _optionals = [
        "text",
        "start_word",
        "end_word",
        "sentiment",
        "sentiment_score",
    ]

    def __init__(
        self,
        text=APIHelper.SKIP,
        start_word=APIHelper.SKIP,
        end_word=APIHelper.SKIP,
        sentiment=APIHelper.SKIP,
        sentiment_score=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SharedSentimentsSegmentsItems instance."""
        # Initialize members of the class
        if text is not APIHelper.SKIP:
            self.text = text
        if start_word is not APIHelper.SKIP:
            self.start_word = start_word
        if end_word is not APIHelper.SKIP:
            self.end_word = end_word
        if sentiment is not APIHelper.SKIP:
            self.sentiment = sentiment
        if sentiment_score is not APIHelper.SKIP:
            self.sentiment_score = sentiment_score

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        text =\
            dictionary.get("text")\
            if dictionary.get("text")\
                else APIHelper.SKIP
        start_word =\
            dictionary.get("start_word")\
            if dictionary.get("start_word")\
                else APIHelper.SKIP
        end_word =\
            dictionary.get("end_word")\
            if dictionary.get("end_word")\
                else APIHelper.SKIP
        sentiment =\
            dictionary.get("sentiment")\
            if dictionary.get("sentiment")\
                else APIHelper.SKIP
        sentiment_score =\
            dictionary.get("sentiment_score")\
            if dictionary.get("sentiment_score")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(text,
                   start_word,
                   end_word,
                   sentiment,
                   sentiment_score,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _start_word=(
            self.start_word
            if hasattr(self, "start_word")
            else None
        )
        _end_word=(
            self.end_word
            if hasattr(self, "end_word")
            else None
        )
        _sentiment=(
            self.sentiment
            if hasattr(self, "sentiment")
            else None
        )
        _sentiment_score=(
            self.sentiment_score
            if hasattr(self, "sentiment_score")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"text={_text!r}, "
            f"start_word={_start_word!r}, "
            f"end_word={_end_word!r}, "
            f"sentiment={_sentiment!r}, "
            f"sentiment_score={_sentiment_score!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _start_word=(
            self.start_word
            if hasattr(self, "start_word")
            else None
        )
        _end_word=(
            self.end_word
            if hasattr(self, "end_word")
            else None
        )
        _sentiment=(
            self.sentiment
            if hasattr(self, "sentiment")
            else None
        )
        _sentiment_score=(
            self.sentiment_score
            if hasattr(self, "sentiment_score")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"text={_text!s}, "
            f"start_word={_start_word!s}, "
            f"end_word={_end_word!s}, "
            f"sentiment={_sentiment!s}, "
            f"sentiment_score={_sentiment_score!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
