"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper
from deepgram.models.usage_fields_v_1_response_models_items import (
    UsageFieldsV1ResponseModelsItems,
)


class UsageFieldsV1Response(object):
    """Implementation of the 'UsageFieldsV1Response' model.

    Attributes:
        tags (List[str]): List of tags associated with the project
        models (List[UsageFieldsV1ResponseModelsItems]): List of models available for
            the project.
        processing_methods (List[str]): Processing methods supported by the API
        features (List[str]): API features available to the project
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tags": "tags",
        "models": "models",
        "processing_methods": "processing_methods",
        "features": "features",
    }

    _optionals = [
        "tags",
        "models",
        "processing_methods",
        "features",
    ]

    def __init__(
        self,
        tags=APIHelper.SKIP,
        models=APIHelper.SKIP,
        processing_methods=APIHelper.SKIP,
        features=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a UsageFieldsV1Response instance."""
        # Initialize members of the class
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if models is not APIHelper.SKIP:
            self.models = models
        if processing_methods is not APIHelper.SKIP:
            self.processing_methods = processing_methods
        if features is not APIHelper.SKIP:
            self.features = features

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        tags =\
            dictionary.get("tags")\
            if dictionary.get("tags")\
                else APIHelper.SKIP
        models = None
        if dictionary.get("models") is not None:
            models = [
                UsageFieldsV1ResponseModelsItems.from_dictionary(x)
                    for x in dictionary.get("models")
            ]
        else:
            models = APIHelper.SKIP
        processing_methods =\
            dictionary.get("processing_methods")\
            if dictionary.get("processing_methods")\
                else APIHelper.SKIP
        features =\
            dictionary.get("features")\
            if dictionary.get("features")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(tags,
                   models,
                   processing_methods,
                   features,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _models=(
            self.models
            if hasattr(self, "models")
            else None
        )
        _processing_methods=(
            self.processing_methods
            if hasattr(self, "processing_methods")
            else None
        )
        _features=(
            self.features
            if hasattr(self, "features")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"tags={_tags!r}, "
            f"models={_models!r}, "
            f"processing_methods={_processing_methods!r}, "
            f"features={_features!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _models=(
            self.models
            if hasattr(self, "models")
            else None
        )
        _processing_methods=(
            self.processing_methods
            if hasattr(self, "processing_methods")
            else None
        )
        _features=(
            self.features
            if hasattr(self, "features")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"tags={_tags!s}, "
            f"models={_models!s}, "
            f"processing_methods={_processing_methods!s}, "
            f"features={_features!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
