"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from deepgram.api_helper import APIHelper
from deepgram.models.usage_v_1_response_resolution import (
    UsageV1ResponseResolution,
)


class UsageV1Response(object):
    """Implementation of the 'UsageV1Response' model.

    Attributes:
        start (date): The model property of type date.
        end (date): The model property of type date.
        resolution (UsageV1ResponseResolution): The model property of type
            UsageV1ResponseResolution.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "start": "start",
        "end": "end",
        "resolution": "resolution",
    }

    _optionals = [
        "start",
        "end",
        "resolution",
    ]

    def __init__(
        self,
        start=APIHelper.SKIP,
        end=APIHelper.SKIP,
        resolution=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a UsageV1Response instance."""
        # Initialize members of the class
        if start is not APIHelper.SKIP:
            self.start = start
        if end is not APIHelper.SKIP:
            self.end = end
        if resolution is not APIHelper.SKIP:
            self.resolution = resolution

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        start = dateutil.parser.parse(
            dictionary.get("start")).date()\
            if dictionary.get("start") else APIHelper.SKIP
        end = dateutil.parser.parse(
            dictionary.get("end")).date()\
            if dictionary.get("end") else APIHelper.SKIP
        resolution =\
            UsageV1ResponseResolution.from_dictionary(
                dictionary.get("resolution"))\
                if "resolution" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(start,
                   end,
                   resolution,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _start=(
            self.start
            if hasattr(self, "start")
            else None
        )
        _end=(
            self.end
            if hasattr(self, "end")
            else None
        )
        _resolution=(
            self.resolution
            if hasattr(self, "resolution")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"start={_start!r}, "
            f"end={_end!r}, "
            f"resolution={_resolution!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _start=(
            self.start
            if hasattr(self, "start")
            else None
        )
        _end=(
            self.end
            if hasattr(self, "end")
            else None
        )
        _resolution=(
            self.resolution
            if hasattr(self, "resolution")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"start={_start!s}, "
            f"end={_end!s}, "
            f"resolution={_resolution!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
