"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from deepgram.api_helper import APIHelper


class UsageFieldsV1ResponseModelsItems(object):
    """Implementation of the 'UsageFieldsV1ResponseModelsItems' model.

    Attributes:
        name (str): Name of the model.
        language (str): The language supported by the model (IETF language tag).
        version (str): Version identifier of the model, typically with a date and a
            revision number.
        model_id (str): Unique identifier for the model.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "language": "language",
        "version": "version",
        "model_id": "model_id",
    }

    _optionals = [
        "name",
        "language",
        "version",
        "model_id",
    ]

    def __init__(
        self,
        name=APIHelper.SKIP,
        language=APIHelper.SKIP,
        version=APIHelper.SKIP,
        model_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a UsageFieldsV1ResponseModelsItems instance."""
        # Initialize members of the class
        if name is not APIHelper.SKIP:
            self.name = name
        if language is not APIHelper.SKIP:
            self.language = language
        if version is not APIHelper.SKIP:
            self.version = version
        if model_id is not APIHelper.SKIP:
            self.model_id = model_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        language =\
            dictionary.get("language")\
            if dictionary.get("language")\
                else APIHelper.SKIP
        version =\
            dictionary.get("version")\
            if dictionary.get("version")\
                else APIHelper.SKIP
        model_id =\
            dictionary.get("model_id")\
            if dictionary.get("model_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   language,
                   version,
                   model_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _language=(
            self.language
            if hasattr(self, "language")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _model_id=(
            self.model_id
            if hasattr(self, "model_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"language={_language!r}, "
            f"version={_version!r}, "
            f"model_id={_model_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _language=(
            self.language
            if hasattr(self, "language")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _model_id=(
            self.model_id
            if hasattr(self, "model_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"language={_language!s}, "
            f"version={_version!s}, "
            f"model_id={_model_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
