"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class V1ListenPostParametersEncoding(object):
    """Implementation of the 'V1ListenPostParametersEncoding' enum.

    Attributes:
        LINEAR16: The enum member of type str.
        FLAC: The enum member of type str.
        MULAW: The enum member of type str.
        AMRNB: The enum member of type str.
        AMRWB: The enum member of type str.
        OPUS: The enum member of type str.
        SPEEX: The enum member of type str.
        G729: The enum member of type str.

    """

    LINEAR16 = "linear16"

    FLAC = "flac"

    MULAW = "mulaw"

    AMRNB = "amr-nb"

    AMRWB = "amr-wb"

    OPUS = "opus"

    SPEEX = "speex"

    G729 = "g729"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
