"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class V1SpeakPostParametersModel(object):
    """Implementation of the 'V1SpeakPostParametersModel' enum.

    Attributes:
        AURAANGUSEN: The enum member of type str.
        AURAARCASEN: The enum member of type str.
        AURAASTERIAEN: The enum member of type str.
        AURAATHENAEN: The enum member of type str.
        AURAHELIOSEN: The enum member of type str.
        AURAHERAEN: The enum member of type str.
        AURALUNAEN: The enum member of type str.
        AURAORIONEN: The enum member of type str.
        AURAORPHEUSEN: The enum member of type str.
        AURAPERSEUSEN: The enum member of type str.
        AURASTELLAEN: The enum member of type str.
        AURAZEUSEN: The enum member of type str.
        AURA2AMALTHEAEN: The enum member of type str.
        AURA2ANDROMEDAEN: The enum member of type str.
        AURA2APOLLOEN: The enum member of type str.
        AURA2ARCASEN: The enum member of type str.
        AURA2ARIESEN: The enum member of type str.
        AURA2ASTERIAEN: The enum member of type str.
        AURA2ATHENAEN: The enum member of type str.
        AURA2ATLASEN: The enum member of type str.
        AURA2AURORAEN: The enum member of type str.
        AURA2CALLISTAEN: The enum member of type str.
        AURA2CORAEN: The enum member of type str.
        AURA2CORDELIAEN: The enum member of type str.
        AURA2DELIAEN: The enum member of type str.
        AURA2DRACOEN: The enum member of type str.
        AURA2ELECTRAEN: The enum member of type str.
        AURA2HARMONIAEN: The enum member of type str.
        AURA2HELENAEN: The enum member of type str.
        AURA2HERAEN: The enum member of type str.
        AURA2HERMESEN: The enum member of type str.
        AURA2HYPERIONEN: The enum member of type str.
        AURA2IRISEN: The enum member of type str.
        AURA2JANUSEN: The enum member of type str.
        AURA2JUNOEN: The enum member of type str.
        AURA2JUPITEREN: The enum member of type str.
        AURA2LUNAEN: The enum member of type str.
        AURA2MARSEN: The enum member of type str.
        AURA2MINERVAEN: The enum member of type str.
        AURA2NEPTUNEEN: The enum member of type str.
        AURA2ODYSSEUSEN: The enum member of type str.
        AURA2OPHELIAEN: The enum member of type str.
        AURA2ORIONEN: The enum member of type str.
        AURA2ORPHEUSEN: The enum member of type str.
        AURA2PANDORAEN: The enum member of type str.
        AURA2PHOEBEEN: The enum member of type str.
        AURA2PLUTOEN: The enum member of type str.
        AURA2SATURNEN: The enum member of type str.
        AURA2SELENEEN: The enum member of type str.
        AURA2THALIAEN: The enum member of type str.
        AURA2THEIAEN: The enum member of type str.
        AURA2VESTAEN: The enum member of type str.
        AURA2ZEUSEN: The enum member of type str.
        AURA2AGUSTINAES: The enum member of type str.
        AURA2ALVAROES: The enum member of type str.
        AURA2ANTONIAES: The enum member of type str.
        AURA2AQUILAES: The enum member of type str.
        AURA2CARINAES: The enum member of type str.
        AURA2CELESTEES: The enum member of type str.
        AURA2DIANAES: The enum member of type str.
        AURA2ESTRELLAES: The enum member of type str.
        AURA2GLORIAES: The enum member of type str.
        AURA2JAVIERES: The enum member of type str.
        AURA2LUCIANOES: The enum member of type str.
        AURA2NESTORES: The enum member of type str.
        AURA2OLIVIAES: The enum member of type str.
        AURA2SELENAES: The enum member of type str.
        AURA2SILVIAES: The enum member of type str.
        AURA2SIRIOES: The enum member of type str.
        AURA2VALERIOES: The enum member of type str.
        AURA2AURELIADE: The enum member of type str.
        AURA2ELARADE: The enum member of type str.
        AURA2FABIANDE: The enum member of type str.
        AURA2JULIUSDE: The enum member of type str.
        AURA2KARADE: The enum member of type str.
        AURA2LARADE: The enum member of type str.
        AURA2VIKTORIADE: The enum member of type str.
        AURA2BEATRIXNL: The enum member of type str.
        AURA2CORNELIANL: The enum member of type str.
        AURA2DAPHNENL: The enum member of type str.
        AURA2HESTIANL: The enum member of type str.
        AURA2LARSNL: The enum member of type str.
        AURA2LEDANL: The enum member of type str.
        AURA2RHEANL: The enum member of type str.
        AURA2ROMANNL: The enum member of type str.
        AURA2SANDERNL: The enum member of type str.
        AURA2AGATHEFR: The enum member of type str.
        AURA2HECTORFR: The enum member of type str.
        AURA2CESAREIT: The enum member of type str.
        AURA2CINZIAIT: The enum member of type str.
        AURA2DEMETRAIT: The enum member of type str.
        AURA2DIONISIOIT: The enum member of type str.
        AURA2ELIOIT: The enum member of type str.
        AURA2FLAVIOIT: The enum member of type str.
        AURA2LIVIAIT: The enum member of type str.
        AURA2MAIAIT: The enum member of type str.
        AURA2MELIAIT: The enum member of type str.
        AURA2PERSEOIT: The enum member of type str.
        AURA2AMAJA: The enum member of type str.
        AURA2EBISUJA: The enum member of type str.
        AURA2FUJINJA: The enum member of type str.
        AURA2IZANAMIJA: The enum member of type str.
        AURA2UZUMEJA: The enum member of type str.

    """

    AURAANGUSEN = "aura-angus-en"

    AURAARCASEN = "aura-arcas-en"

    AURAASTERIAEN = "aura-asteria-en"

    AURAATHENAEN = "aura-athena-en"

    AURAHELIOSEN = "aura-helios-en"

    AURAHERAEN = "aura-hera-en"

    AURALUNAEN = "aura-luna-en"

    AURAORIONEN = "aura-orion-en"

    AURAORPHEUSEN = "aura-orpheus-en"

    AURAPERSEUSEN = "aura-perseus-en"

    AURASTELLAEN = "aura-stella-en"

    AURAZEUSEN = "aura-zeus-en"

    AURA2AMALTHEAEN = "aura-2-amalthea-en"

    AURA2ANDROMEDAEN = "aura-2-andromeda-en"

    AURA2APOLLOEN = "aura-2-apollo-en"

    AURA2ARCASEN = "aura-2-arcas-en"

    AURA2ARIESEN = "aura-2-aries-en"

    AURA2ASTERIAEN = "aura-2-asteria-en"

    AURA2ATHENAEN = "aura-2-athena-en"

    AURA2ATLASEN = "aura-2-atlas-en"

    AURA2AURORAEN = "aura-2-aurora-en"

    AURA2CALLISTAEN = "aura-2-callista-en"

    AURA2CORAEN = "aura-2-cora-en"

    AURA2CORDELIAEN = "aura-2-cordelia-en"

    AURA2DELIAEN = "aura-2-delia-en"

    AURA2DRACOEN = "aura-2-draco-en"

    AURA2ELECTRAEN = "aura-2-electra-en"

    AURA2HARMONIAEN = "aura-2-harmonia-en"

    AURA2HELENAEN = "aura-2-helena-en"

    AURA2HERAEN = "aura-2-hera-en"

    AURA2HERMESEN = "aura-2-hermes-en"

    AURA2HYPERIONEN = "aura-2-hyperion-en"

    AURA2IRISEN = "aura-2-iris-en"

    AURA2JANUSEN = "aura-2-janus-en"

    AURA2JUNOEN = "aura-2-juno-en"

    AURA2JUPITEREN = "aura-2-jupiter-en"

    AURA2LUNAEN = "aura-2-luna-en"

    AURA2MARSEN = "aura-2-mars-en"

    AURA2MINERVAEN = "aura-2-minerva-en"

    AURA2NEPTUNEEN = "aura-2-neptune-en"

    AURA2ODYSSEUSEN = "aura-2-odysseus-en"

    AURA2OPHELIAEN = "aura-2-ophelia-en"

    AURA2ORIONEN = "aura-2-orion-en"

    AURA2ORPHEUSEN = "aura-2-orpheus-en"

    AURA2PANDORAEN = "aura-2-pandora-en"

    AURA2PHOEBEEN = "aura-2-phoebe-en"

    AURA2PLUTOEN = "aura-2-pluto-en"

    AURA2SATURNEN = "aura-2-saturn-en"

    AURA2SELENEEN = "aura-2-selene-en"

    AURA2THALIAEN = "aura-2-thalia-en"

    AURA2THEIAEN = "aura-2-theia-en"

    AURA2VESTAEN = "aura-2-vesta-en"

    AURA2ZEUSEN = "aura-2-zeus-en"

    AURA2AGUSTINAES = "aura-2-agustina-es"

    AURA2ALVAROES = "aura-2-alvaro-es"

    AURA2ANTONIAES = "aura-2-antonia-es"

    AURA2AQUILAES = "aura-2-aquila-es"

    AURA2CARINAES = "aura-2-carina-es"

    AURA2CELESTEES = "aura-2-celeste-es"

    AURA2DIANAES = "aura-2-diana-es"

    AURA2ESTRELLAES = "aura-2-estrella-es"

    AURA2GLORIAES = "aura-2-gloria-es"

    AURA2JAVIERES = "aura-2-javier-es"

    AURA2LUCIANOES = "aura-2-luciano-es"

    AURA2NESTORES = "aura-2-nestor-es"

    AURA2OLIVIAES = "aura-2-olivia-es"

    AURA2SELENAES = "aura-2-selena-es"

    AURA2SILVIAES = "aura-2-silvia-es"

    AURA2SIRIOES = "aura-2-sirio-es"

    AURA2VALERIOES = "aura-2-valerio-es"

    AURA2AURELIADE = "aura-2-aurelia-de"

    AURA2ELARADE = "aura-2-elara-de"

    AURA2FABIANDE = "aura-2-fabian-de"

    AURA2JULIUSDE = "aura-2-julius-de"

    AURA2KARADE = "aura-2-kara-de"

    AURA2LARADE = "aura-2-lara-de"

    AURA2VIKTORIADE = "aura-2-viktoria-de"

    AURA2BEATRIXNL = "aura-2-beatrix-nl"

    AURA2CORNELIANL = "aura-2-cornelia-nl"

    AURA2DAPHNENL = "aura-2-daphne-nl"

    AURA2HESTIANL = "aura-2-hestia-nl"

    AURA2LARSNL = "aura-2-lars-nl"

    AURA2LEDANL = "aura-2-leda-nl"

    AURA2RHEANL = "aura-2-rhea-nl"

    AURA2ROMANNL = "aura-2-roman-nl"

    AURA2SANDERNL = "aura-2-sander-nl"

    AURA2AGATHEFR = "aura-2-agathe-fr"

    AURA2HECTORFR = "aura-2-hector-fr"

    AURA2CESAREIT = "aura-2-cesare-it"

    AURA2CINZIAIT = "aura-2-cinzia-it"

    AURA2DEMETRAIT = "aura-2-demetra-it"

    AURA2DIONISIOIT = "aura-2-dionisio-it"

    AURA2ELIOIT = "aura-2-elio-it"

    AURA2FLAVIOIT = "aura-2-flavio-it"

    AURA2LIVIAIT = "aura-2-livia-it"

    AURA2MAIAIT = "aura-2-maia-it"

    AURA2MELIAIT = "aura-2-melia-it"

    AURA2PERSEOIT = "aura-2-perseo-it"

    AURA2AMAJA = "aura-2-ama-ja"

    AURA2EBISUJA = "aura-2-ebisu-ja"

    AURA2FUJINJA = "aura-2-fujin-ja"

    AURA2IZANAMIJA = "aura-2-izanami-ja"

    AURA2UZUMEJA = "aura-2-uzume-ja"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
