"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems(object):
    """Implementation of the
    'V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems' enum.

    Attributes:
        ENUM_SELFHOSTEDPRODUCTS: The enum member of type str.
        ENUM_SELFHOSTEDPRODUCTAPI: The enum member of type str.
        ENUM_SELFHOSTEDPRODUCTENGINE: The enum member of type str.
        ENUM_SELFHOSTEDPRODUCTLICENSEPROXY: The enum member of type str.
        ENUM_SELFHOSTEDPRODUCTDGTOOLS: The enum member of type str.
        ENUM_SELFHOSTEDPRODUCTBILLING: The enum member of type str.
        ENUM_SELFHOSTEDPRODUCTHOTPEPPER: The enum member of type str.
        ENUM_SELFHOSTEDPRODUCTMETRICSSERVER: The enum member of type str.

    """

    ENUM_SELFHOSTEDPRODUCTS = "self-hosted:products"

    ENUM_SELFHOSTEDPRODUCTAPI = "self-hosted:product:api"

    ENUM_SELFHOSTEDPRODUCTENGINE = "self-hosted:product:engine"

    ENUM_SELFHOSTEDPRODUCTLICENSEPROXY = "self-hosted:product:license-proxy"

    ENUM_SELFHOSTEDPRODUCTDGTOOLS = "self-hosted:product:dgtools"

    ENUM_SELFHOSTEDPRODUCTBILLING = "self-hosted:product:billing"

    ENUM_SELFHOSTEDPRODUCTHOTPEPPER = "self-hosted:product:hotpepper"

    ENUM_SELFHOSTEDPRODUCTMETRICSSERVER = "self-hosted:product:metrics-server"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
