"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class V1ProjectsProjectIdUsageBreakdownGetParametersGrouping(object):
    """Implementation of the
    'V1ProjectsProjectIdUsageBreakdownGetParametersGrouping' enum.

    Attributes:
        ACCESSOR: The enum member of type str.
        ENDPOINT: The enum member of type str.
        FEATURE_SET: The enum member of type str.
        MODELS: The enum member of type str.
        METHOD: The enum member of type str.
        TAGS: The enum member of type str.
        DEPLOYMENT: The enum member of type str.

    """

    ACCESSOR = "accessor"

    ENDPOINT = "endpoint"

    FEATURE_SET = "feature_set"

    MODELS = "models"

    METHOD = "method"

    TAGS = "tags"

    DEPLOYMENT = "deployment"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
