
"""
restapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: E501
from __future__ import annotations

from typing import (
    Callable,
    ClassVar,
)

from apimatic_core.types.union_types.leaf_type import (
    LeafType,
)
from apimatic_core.types.union_types.one_of import (
    OneOf,
)
from apimatic_core.types.union_types.union_type_context import (
    UnionTypeContext as Context,
)

from restapi.models.agent_think_models_v_1_response_models_items_0 import (
    AgentThinkModelsV1ResponseModelsItems0,
)
from restapi.models.agent_think_models_v_1_response_models_items_1 import (
    AgentThinkModelsV1ResponseModelsItems1,
)
from restapi.models.agent_think_models_v_1_response_models_items_2 import (
    AgentThinkModelsV1ResponseModelsItems2,
)
from restapi.models.agent_think_models_v_1_response_models_items_3 import (
    AgentThinkModelsV1ResponseModelsItems3,
)
from restapi.models.agent_think_models_v_1_response_models_items_4 import (
    AgentThinkModelsV1ResponseModelsItems4,
)
from restapi.models.get_model_v_1_response_0 import (
    GetModelV1Response0,
)
from restapi.models.get_model_v_1_response_1 import (
    GetModelV1Response1,
)
from restapi.models.listen_v_1_accepted_response import (
    ListenV1AcceptedResponse,
)
from restapi.models.listen_v_1_response import (
    ListenV1Response,
)
from restapi.models.read_v_1_request_text import (
    ReadV1RequestText,
)
from restapi.models.read_v_1_request_url import (
    ReadV1RequestUrl,
)
from restapi.models.v_1_listen_post_parameters_model_0 import (
    V1ListenPostParametersModel0,
)
from restapi.models.v_1_listen_post_parameters_redact_schema_one_of_1_items import (
    V1ListenPostParametersRedactSchemaOneOf1Items,
)
from restapi.models.v_1_listen_post_parameters_summarize_0 import (
    V1ListenPostParametersSummarize0,
)
from restapi.models.v_1_listen_post_parameters_version_0 import (
    V1ListenPostParametersVersion0,
)
from restapi.models.v_1_read_post_parameters_summarize_0 import (
    V1ReadPostParametersSummarize0,
)
from restapi.models.v_1_speak_post_parameters_bit_rate_0 import (
    V1SpeakPostParametersBitRate0,
)
from restapi.models.v_1_speak_post_parameters_container_0 import (
    V1SpeakPostParametersContainer0,
)
from restapi.models.v_1_speak_post_parameters_container_1 import (
    V1SpeakPostParametersContainer1,
)
from restapi.models.v_1_speak_post_parameters_container_2 import (
    V1SpeakPostParametersContainer2,
)
from restapi.models.v_1_speak_post_parameters_container_3 import (
    V1SpeakPostParametersContainer3,
)
from restapi.models.v_1_speak_post_parameters_container_4 import (
    V1SpeakPostParametersContainer4,
)
from restapi.models.v_1_speak_post_parameters_encoding_0 import (
    V1SpeakPostParametersEncoding0,
)
from restapi.models.v_1_speak_post_parameters_encoding_1 import (
    V1SpeakPostParametersEncoding1,
)
from restapi.models.v_1_speak_post_parameters_encoding_2 import (
    V1SpeakPostParametersEncoding2,
)
from restapi.models.v_1_speak_post_parameters_encoding_3 import (
    V1SpeakPostParametersEncoding3,
)
from restapi.models.v_1_speak_post_parameters_encoding_4 import (
    V1SpeakPostParametersEncoding4,
)
from restapi.models.v_1_speak_post_parameters_encoding_5 import (
    V1SpeakPostParametersEncoding5,
)
from restapi.models.v_1_speak_post_parameters_encoding_6 import (
    V1SpeakPostParametersEncoding6,
)
from restapi.models.v_1_speak_post_parameters_sample_rate_0 import (
    V1SpeakPostParametersSampleRate0,
)
from restapi.models.v_1_speak_post_parameters_sample_rate_1 import (
    V1SpeakPostParametersSampleRate1,
)
from restapi.models.v_1_speak_post_parameters_sample_rate_2 import (
    V1SpeakPostParametersSampleRate2,
)
from restapi.models.v_1_speak_post_parameters_sample_rate_3 import (
    V1SpeakPostParametersSampleRate3,
)
from restapi.models.v_1_speak_post_parameters_sample_rate_4 import (
    V1SpeakPostParametersSampleRate4,
)
from restapi.models.v_2_speak_post_parameters_bit_rate_0 import (
    V2SpeakPostParametersBitRate0,
)
from restapi.models.v_2_speak_post_parameters_container_0 import (
    V2SpeakPostParametersContainer0,
)
from restapi.models.v_2_speak_post_parameters_container_1 import (
    V2SpeakPostParametersContainer1,
)
from restapi.models.v_2_speak_post_parameters_container_2 import (
    V2SpeakPostParametersContainer2,
)
from restapi.models.v_2_speak_post_parameters_container_3 import (
    V2SpeakPostParametersContainer3,
)
from restapi.models.v_2_speak_post_parameters_container_4 import (
    V2SpeakPostParametersContainer4,
)
from restapi.models.v_2_speak_post_parameters_encoding_0 import (
    V2SpeakPostParametersEncoding0,
)
from restapi.models.v_2_speak_post_parameters_encoding_1 import (
    V2SpeakPostParametersEncoding1,
)
from restapi.models.v_2_speak_post_parameters_encoding_2 import (
    V2SpeakPostParametersEncoding2,
)
from restapi.models.v_2_speak_post_parameters_encoding_3 import (
    V2SpeakPostParametersEncoding3,
)
from restapi.models.v_2_speak_post_parameters_encoding_4 import (
    V2SpeakPostParametersEncoding4,
)
from restapi.models.v_2_speak_post_parameters_encoding_5 import (
    V2SpeakPostParametersEncoding5,
)
from restapi.models.v_2_speak_post_parameters_encoding_6 import (
    V2SpeakPostParametersEncoding6,
)
from restapi.models.v_2_speak_post_parameters_sample_rate_0 import (
    V2SpeakPostParametersSampleRate0,
)
from restapi.models.v_2_speak_post_parameters_sample_rate_1 import (
    V2SpeakPostParametersSampleRate1,
)
from restapi.models.v_2_speak_post_parameters_sample_rate_2 import (
    V2SpeakPostParametersSampleRate2,
)
from restapi.models.v_2_speak_post_parameters_sample_rate_3 import (
    V2SpeakPostParametersSampleRate3,
)


class UnionTypeLookUp:
    """
    Provides lookup and factory methods for predefined union type templates.
    This class stores a mapping of template names to callables that construct
    union type instances. These templates are used to describe compatible
    data shapes by combining primitive or model-based types into a single
    resolved representation at runtime.

    Attributes:
        _templates (dict): A mapping of template names to factory callables
        that create configured union types.

    """

    _templates: ClassVar[dict[str, Callable]] = {
        "V1ListenPostParametersExtra": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ListenPostParametersSummarize": lambda: OneOf(
            [
                LeafType(V1ListenPostParametersSummarize0),
                LeafType(bool),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ListenPostParametersTag": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ListenPostParametersCustomTopic": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ListenPostParametersCustomIntent": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ListenPostParametersDetectLanguage": lambda: OneOf(
            [
                LeafType(bool),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ListenPostParametersKeywords": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "TranscribeModel": lambda: OneOf(
            [
                LeafType(V1ListenPostParametersModel0),
                LeafType(str),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "TranscribeRedact": lambda: OneOf(
            [
                LeafType(str),
                LeafType(V1ListenPostParametersRedactSchemaOneOf1Items,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ListenPostParametersReplace": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ListenPostParametersSearch": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "TranscribeVersion": lambda: OneOf(
            [
                LeafType(V1ListenPostParametersVersion0),
                LeafType(str),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "listen_v1_media_transcribe_Response_200": lambda: OneOf(
            [
                LeafType(ListenV1Response),
                LeafType(ListenV1AcceptedResponse),
            ],
        ),
        "V1SpeakPostParametersTag": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GenerateBitRate": lambda: OneOf(
            [
                LeafType(V1SpeakPostParametersBitRate0),
                LeafType(float),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GenerateContainer": lambda: OneOf(
            [
                LeafType(V1SpeakPostParametersContainer0),
                LeafType(V1SpeakPostParametersContainer1),
                LeafType(V1SpeakPostParametersContainer2),
                LeafType(V1SpeakPostParametersContainer3),
                LeafType(V1SpeakPostParametersContainer4),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GenerateEncoding": lambda: OneOf(
            [
                LeafType(V1SpeakPostParametersEncoding0),
                LeafType(V1SpeakPostParametersEncoding1),
                LeafType(V1SpeakPostParametersEncoding2),
                LeafType(V1SpeakPostParametersEncoding3),
                LeafType(V1SpeakPostParametersEncoding4),
                LeafType(V1SpeakPostParametersEncoding5),
                LeafType(V1SpeakPostParametersEncoding6),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GenerateSampleRate": lambda: OneOf(
            [
                LeafType(V1SpeakPostParametersSampleRate0),
                LeafType(V1SpeakPostParametersSampleRate1),
                LeafType(V1SpeakPostParametersSampleRate2),
                LeafType(V1SpeakPostParametersSampleRate3),
                LeafType(V1SpeakPostParametersSampleRate4),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ReadPostParametersSummarize": lambda: OneOf(
            [
                LeafType(V1ReadPostParametersSummarize0),
                LeafType(bool),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ReadPostParametersTag": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ReadPostParametersCustomTopic": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V1ReadPostParametersCustomIntent": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "ReadV1Request": lambda: OneOf(
            [
                LeafType(ReadV1RequestUrl),
                LeafType(ReadV1RequestText),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GetModelV1Response": lambda: OneOf(
            [
                LeafType(GetModelV1Response0),
                LeafType(GetModelV1Response1),
            ],
        ),
        "CreateKeyV1Request": lambda: OneOf(
            [
                LeafType(object),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "V2SpeakPostParametersTag": lambda: OneOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GenerateBitRate2": lambda: OneOf(
            [
                LeafType(V2SpeakPostParametersBitRate0),
                LeafType(int),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GenerateContainer2": lambda: OneOf(
            [
                LeafType(V2SpeakPostParametersContainer0),
                LeafType(V2SpeakPostParametersContainer1),
                LeafType(V2SpeakPostParametersContainer2),
                LeafType(V2SpeakPostParametersContainer3),
                LeafType(V2SpeakPostParametersContainer4),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GenerateEncoding2": lambda: OneOf(
            [
                LeafType(V2SpeakPostParametersEncoding0),
                LeafType(V2SpeakPostParametersEncoding1),
                LeafType(V2SpeakPostParametersEncoding2),
                LeafType(V2SpeakPostParametersEncoding3),
                LeafType(V2SpeakPostParametersEncoding4),
                LeafType(V2SpeakPostParametersEncoding5),
                LeafType(V2SpeakPostParametersEncoding6),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GenerateSampleRate2": lambda: OneOf(
            [
                LeafType(V2SpeakPostParametersSampleRate0),
                LeafType(V2SpeakPostParametersSampleRate1),
                LeafType(V2SpeakPostParametersSampleRate2),
                LeafType(V2SpeakPostParametersSampleRate3),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "AgentThinkModelsV1ResponseModelsItems": lambda: OneOf(
            [
                LeafType(AgentThinkModelsV1ResponseModelsItems0),
                LeafType(AgentThinkModelsV1ResponseModelsItems1),
                LeafType(AgentThinkModelsV1ResponseModelsItems2),
                LeafType(AgentThinkModelsV1ResponseModelsItems3),
                LeafType(AgentThinkModelsV1ResponseModelsItems4),
            ],
            Context.create(
               is_array=True,
            ),
        ),
    }

    @staticmethod
    def get(name):
        """
        Retrieve and construct a union type template by name.

        Args:
            name (str): The key identifying the template to resolve.

        Returns:
            Any: A new instance of the union type defined for the given name.

        Raises:
            KeyError: If no template exists for the specified name.

        """
        return UnionTypeLookUp._templates[name]()
