"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class AgentThinkModelsV1ResponseModelsItemsOneOf2Id(object):
    """Implementation of the 'AgentThinkModelsV1ResponseModelsItemsOneOf2Id' enum.

    The unique identifier of the Google model

    Attributes:
        ENUM_GEMINI25FLASH: The enum member of type str.
        ENUM_GEMINI20FLASH: The enum member of type str.
        ENUM_GEMINI20FLASHLITE: The enum member of type str.

    """

    _all_values = ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-2.0-flash-lite"]
    ENUM_GEMINI25FLASH = "gemini-2.5-flash"

    ENUM_GEMINI20FLASH = "gemini-2.0-flash"

    ENUM_GEMINI20FLASHLITE = "gemini-2.0-flash-lite"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
