"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class AgentVariableV1(object):
    """Implementation of the 'AgentVariableV1' model.

    A template variable for agent configurations

    Attributes:
        variable_id (str): The unique identifier of the variable
        key (str): The variable name, following the DG_<VARIABLE_NAME> format
        value (Any): The value to substitute. Can be any valid JSON type
        created_at (datetime): Timestamp when the variable was created
        updated_at (datetime): Timestamp when the variable was last updated
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "variable_id": "variable_id",
        "key": "key",
        "value": "value",
        "created_at": "created_at",
        "updated_at": "updated_at",
    }

    _optionals = [
        "created_at",
        "updated_at",
    ]

    def __init__(
        self,
        variable_id=None,
        key=None,
        value=None,
        created_at=APIHelper.SKIP,
        updated_at=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AgentVariableV1 instance."""
        # Initialize members of the class
        self.variable_id = variable_id
        self.key = key
        self.value = value
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if updated_at is not APIHelper.SKIP:
            self.updated_at =\
                 APIHelper.apply_datetime_converter(
                updated_at, APIHelper.RFC3339DateTime)\
                 if updated_at else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        variable_id =\
            dictionary.get("variable_id")\
            if dictionary.get("variable_id")\
                else None
        key =\
            dictionary.get("key")\
            if dictionary.get("key")\
                else None
        value =\
            dictionary.get("value")\
            if dictionary.get("value")\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else APIHelper.SKIP
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(variable_id,
                   key,
                   value,
                   created_at,
                   updated_at,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _variable_id=self.variable_id
        _key=self.key
        _value=self.value
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"variable_id={_variable_id!r}, "
            f"key={_key!r}, "
            f"value={_value!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _variable_id=self.variable_id
        _key=self.key
        _value=self.value
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"variable_id={_variable_id!s}, "
            f"key={_key!s}, "
            f"value={_value!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
