"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class AgentThinkModelsV1Response(object):
    """Implementation of the 'AgentThinkModelsV1Response' model.

    Attributes:
        models (List[AgentThinkModelsV1ResponseModelsItems0 |
            AgentThinkModelsV1ResponseModelsItems1 |
            AgentThinkModelsV1ResponseModelsItems2 |
            AgentThinkModelsV1ResponseModelsItems3 |
            AgentThinkModelsV1ResponseModelsItems4]): The model property of type
            List[AgentThinkModelsV1ResponseModelsItems0 |
            AgentThinkModelsV1ResponseModelsItems1 |
            AgentThinkModelsV1ResponseModelsItems2 |
            AgentThinkModelsV1ResponseModelsItems3 |
            AgentThinkModelsV1ResponseModelsItems4].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "models": "models",
    }

    def __init__(
        self,
        models=None,
        additional_properties=None):
        """Initialize a AgentThinkModelsV1Response instance."""
        # Initialize members of the class
        self.models = models

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from restapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        models = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("AgentThinkModelsV1ResponseModelsItems"),
            dictionary.get("models"),
            False)\
            if dictionary.get("models") is not None\
            else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(models,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from restapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return (UnionTypeLookUp.get("AgentThinkModelsV1ResponseModelsItems")
                .validate(dictionary.models).is_valid)

        if not isinstance(dictionary, dict):
            return False

        return (UnionTypeLookUp.get("AgentThinkModelsV1ResponseModelsItems")
            .validate(dictionary.get("models")).is_valid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _models=self.models
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"models={_models!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _models=self.models
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"models={_models!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
