"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from restapi.api_helper import APIHelper
from restapi.models.billing_breakdown_v_1_response_resolution import (
    BillingBreakdownV1ResponseResolution,
)
from restapi.models.billing_breakdown_v_1_response_results_items import (
    BillingBreakdownV1ResponseResultsItems,
)


class BillingBreakdownV1Response(object):
    """Implementation of the 'BillingBreakdownV1Response' model.

    Attributes:
        start (date): Start date of the billing summmary period
        end (date): End date of the billing summary period
        resolution (BillingBreakdownV1ResponseResolution): The model property of type
            BillingBreakdownV1ResponseResolution.
        results (List[BillingBreakdownV1ResponseResultsItems]): The model property of
            type List[BillingBreakdownV1ResponseResultsItems].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "start": "start",
        "end": "end",
        "resolution": "resolution",
        "results": "results",
    }

    def __init__(
        self,
        start=None,
        end=None,
        resolution=None,
        results=None,
        additional_properties=None):
        """Initialize a BillingBreakdownV1Response instance."""
        # Initialize members of the class
        self.start = start
        self.end = end
        self.resolution = resolution
        self.results = results

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        start = dateutil.parser.parse(
            dictionary.get("start")).date()\
            if dictionary.get("start") else None
        end = dateutil.parser.parse(
            dictionary.get("end")).date()\
            if dictionary.get("end") else None
        resolution =\
            BillingBreakdownV1ResponseResolution.from_dictionary(
                dictionary.get("resolution"))\
                if dictionary.get("resolution") else None
        results = None
        if dictionary.get("results") is not None:
            results = [
                BillingBreakdownV1ResponseResultsItems.from_dictionary(x)
                    for x in dictionary.get("results")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(start,
                   end,
                   resolution,
                   results,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _start=self.start
        _end=self.end
        _resolution=self.resolution
        _results=self.results
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"start={_start!r}, "
            f"end={_end!r}, "
            f"resolution={_resolution!r}, "
            f"results={_results!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _start=self.start
        _end=self.end
        _resolution=self.resolution
        _results=self.results
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"start={_start!s}, "
            f"end={_end!s}, "
            f"resolution={_resolution!s}, "
            f"results={_results!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
