"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class CreateAgentVariableV1Request(object):
    """Implementation of the 'CreateAgentVariableV1Request' model.

    Request body for creating an agent variable

    Attributes:
        key (str): The variable name, following the DG_<VARIABLE_NAME> format
        value (Any): The value to substitute. Can be any valid JSON type (string,
            number, boolean, object, or array)
        api_version (int): API version. Defaults to 1
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key": "key",
        "value": "value",
        "api_version": "api_version",
    }

    _optionals = [
        "api_version",
    ]

    def __init__(
        self,
        key=None,
        value=None,
        api_version=1,
        additional_properties=None):
        """Initialize a CreateAgentVariableV1Request instance."""
        # Initialize members of the class
        self.key = key
        self.value = value
        self.api_version = api_version

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        key =\
            dictionary.get("key")\
            if dictionary.get("key")\
                else None
        value =\
            dictionary.get("value")\
            if dictionary.get("value")\
                else None
        api_version =\
            dictionary.get("api_version")\
            if dictionary.get("api_version")\
                else 1

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(key,
                   value,
                   api_version,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _key=self.key
        _value=self.value
        _api_version=(
            self.api_version
            if hasattr(self, "api_version")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key={_key!r}, "
            f"value={_value!r}, "
            f"api_version={_api_version!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _key=self.key
        _value=self.value
        _api_version=(
            self.api_version
            if hasattr(self, "api_version")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key={_key!s}, "
            f"value={_value!s}, "
            f"api_version={_api_version!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
