"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class CreateAgentConfigurationV1Response(object):
    """Implementation of the 'CreateAgentConfigurationV1Response' model.

    Attributes:
        agent_id (str): The unique identifier of the newly created agent configuration
        config (Any): The parsed agent configuration object
        metadata (Dict[str, str]): Metadata associated with the agent configuration
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "agent_id": "agent_id",
        "config": "config",
        "metadata": "metadata",
    }

    _optionals = [
        "metadata",
    ]

    def __init__(
        self,
        agent_id=None,
        config=None,
        metadata=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateAgentConfigurationV1Response instance."""
        # Initialize members of the class
        self.agent_id = agent_id
        self.config = config
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        agent_id =\
            dictionary.get("agent_id")\
            if dictionary.get("agent_id")\
                else None
        config =\
            dictionary.get("config")\
            if dictionary.get("config")\
                else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(agent_id,
                   config,
                   metadata,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _agent_id=self.agent_id
        _config=self.config
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"agent_id={_agent_id!r}, "
            f"config={_config!r}, "
            f"metadata={_metadata!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _agent_id=self.agent_id
        _config=self.config
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"agent_id={_agent_id!s}, "
            f"config={_config!s}, "
            f"metadata={_metadata!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
