"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class ErrorResponseModernError(object):
    """Implementation of the 'ErrorResponseModernError' model.

    Attributes:
        category (str): The category of the error
        message (str): A message about the error
        details (str): A description of the error
        request_id (str): The unique identifier of the request
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "category": "category",
        "message": "message",
        "details": "details",
        "request_id": "request_id",
    }

    _optionals = [
        "category",
        "message",
        "details",
        "request_id",
    ]

    def __init__(
        self,
        category=APIHelper.SKIP,
        message=APIHelper.SKIP,
        details=APIHelper.SKIP,
        request_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ErrorResponseModernError instance."""
        # Initialize members of the class
        if category is not APIHelper.SKIP:
            self.category = category
        if message is not APIHelper.SKIP:
            self.message = message
        if details is not APIHelper.SKIP:
            self.details = details
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        category =\
            dictionary.get("category")\
            if dictionary.get("category")\
                else APIHelper.SKIP
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else APIHelper.SKIP
        details =\
            dictionary.get("details")\
            if dictionary.get("details")\
                else APIHelper.SKIP
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(category,
                   message,
                   details,
                   request_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _category=(
            self.category
            if hasattr(self, "category")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _details=(
            self.details
            if hasattr(self, "details")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"category={_category!r}, "
            f"message={_message!r}, "
            f"details={_details!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _category=(
            self.category
            if hasattr(self, "category")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _details=(
            self.details
            if hasattr(self, "details")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"category={_category!s}, "
            f"message={_message!s}, "
            f"details={_details!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
