"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.project_request_response import (
    ProjectRequestResponse,
)


class GetProjectRequestV1Response(object):
    """Implementation of the 'GetProjectRequestV1Response' model.

    Attributes:
        request (ProjectRequestResponse): A single request
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "request": "request",
    }

    _optionals = [
        "request",
    ]

    def __init__(
        self,
        request=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GetProjectRequestV1Response instance."""
        # Initialize members of the class
        if request is not APIHelper.SKIP:
            self.request = request

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        request =\
            ProjectRequestResponse.from_dictionary(
                dictionary.get("request"))\
                if "request" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(request,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _request=(
            self.request
            if hasattr(self, "request")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"request={_request!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _request=(
            self.request
            if hasattr(self, "request")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"request={_request!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
