"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.get_project_key_v_1_response_item_member_api_key import (
    GetProjectKeyV1ResponseItemMemberApiKey,
)


class GetProjectKeyV1ResponseItemMember(object):
    """Implementation of the 'GetProjectKeyV1ResponseItemMember' model.

    Attributes:
        member_id (str): The model property of type str.
        email (str): The model property of type str.
        first_name (str): The model property of type str.
        last_name (str): The model property of type str.
        api_key (GetProjectKeyV1ResponseItemMemberApiKey): The model property of type
            GetProjectKeyV1ResponseItemMemberApiKey.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "member_id": "member_id",
        "email": "email",
        "first_name": "first_name",
        "last_name": "last_name",
        "api_key": "api_key",
    }

    _optionals = [
        "member_id",
        "email",
        "first_name",
        "last_name",
        "api_key",
    ]

    def __init__(
        self,
        member_id=APIHelper.SKIP,
        email=APIHelper.SKIP,
        first_name=APIHelper.SKIP,
        last_name=APIHelper.SKIP,
        api_key=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GetProjectKeyV1ResponseItemMember instance."""
        # Initialize members of the class
        if member_id is not APIHelper.SKIP:
            self.member_id = member_id
        if email is not APIHelper.SKIP:
            self.email = email
        if first_name is not APIHelper.SKIP:
            self.first_name = first_name
        if last_name is not APIHelper.SKIP:
            self.last_name = last_name
        if api_key is not APIHelper.SKIP:
            self.api_key = api_key

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        member_id =\
            dictionary.get("member_id")\
            if dictionary.get("member_id")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        first_name =\
            dictionary.get("first_name")\
            if dictionary.get("first_name")\
                else APIHelper.SKIP
        last_name =\
            dictionary.get("last_name")\
            if dictionary.get("last_name")\
                else APIHelper.SKIP
        api_key =\
            GetProjectKeyV1ResponseItemMemberApiKey.from_dictionary(
                dictionary.get("api_key"))\
                if "api_key" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(member_id,
                   email,
                   first_name,
                   last_name,
                   api_key,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _member_id=(
            self.member_id
            if hasattr(self, "member_id")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member_id={_member_id!r}, "
            f"email={_email!r}, "
            f"first_name={_first_name!r}, "
            f"last_name={_last_name!r}, "
            f"api_key={_api_key!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _member_id=(
            self.member_id
            if hasattr(self, "member_id")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member_id={_member_id!s}, "
            f"email={_email!s}, "
            f"first_name={_first_name!s}, "
            f"last_name={_last_name!s}, "
            f"api_key={_api_key!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
