"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class GetProjectV1Response(object):
    """Implementation of the 'GetProjectV1Response' model.

    Attributes:
        project_id (str): The unique identifier of the project
        mip_opt_out (bool): Model Improvement Program opt-out
        name (str): The name of the project
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "project_id": "project_id",
        "mip_opt_out": "mip_opt_out",
        "name": "name",
    }

    _optionals = [
        "project_id",
        "mip_opt_out",
        "name",
    ]

    def __init__(
        self,
        project_id=APIHelper.SKIP,
        mip_opt_out=APIHelper.SKIP,
        name=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GetProjectV1Response instance."""
        # Initialize members of the class
        if project_id is not APIHelper.SKIP:
            self.project_id = project_id
        if mip_opt_out is not APIHelper.SKIP:
            self.mip_opt_out = mip_opt_out
        if name is not APIHelper.SKIP:
            self.name = name

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        project_id =\
            dictionary.get("project_id")\
            if dictionary.get("project_id")\
                else APIHelper.SKIP
        mip_opt_out =\
            dictionary.get("mip_opt_out")\
            if "mip_opt_out" in dictionary.keys()\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(project_id,
                   mip_opt_out,
                   name,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _project_id=(
            self.project_id
            if hasattr(self, "project_id")
            else None
        )
        _mip_opt_out=(
            self.mip_opt_out
            if hasattr(self, "mip_opt_out")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"project_id={_project_id!r}, "
            f"mip_opt_out={_mip_opt_out!r}, "
            f"name={_name!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _project_id=(
            self.project_id
            if hasattr(self, "project_id")
            else None
        )
        _mip_opt_out=(
            self.mip_opt_out
            if hasattr(self, "mip_opt_out")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"project_id={_project_id!s}, "
            f"mip_opt_out={_mip_opt_out!s}, "
            f"name={_name!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
