"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.get_project_distribution_credentials_v_1_response_distribution_credentials import (  # noqa: E501
    GetProjectDistributionCredentialsV1ResponseDistributionCredentials,
)
from restapi.models.get_project_distribution_credentials_v_1_response_member import (
    GetProjectDistributionCredentialsV1ResponseMember,
)


class GetProjectDistributionCredentialsV1Response(object):
    """Implementation of the 'GetProjectDistributionCredentialsV1Response' model.

    Attributes:
        member (GetProjectDistributionCredentialsV1ResponseMember): The model
            property of type GetProjectDistributionCredentialsV1ResponseMember.
        distribution_credentials
            (GetProjectDistributionCredentialsV1ResponseDistributionCredentials): The
            model property of type
            GetProjectDistributionCredentialsV1ResponseDistributionCredentials.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "member": "member",
        "distribution_credentials": "distribution_credentials",
    }

    def __init__(
        self,
        member=None,
        distribution_credentials=None,
        additional_properties=None):
        """Initialize a GetProjectDistributionCredentialsV1Response instance."""
        # Initialize members of the class
        self.member = member
        self.distribution_credentials = distribution_credentials

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        member =\
            GetProjectDistributionCredentialsV1ResponseMember.from_dictionary(
                dictionary.get("member"))\
                if dictionary.get("member") else None
        distribution_credentials =\
            GetProjectDistributionCredentialsV1ResponseDistributionCredentials.from_dictionary(
                dictionary.get("distribution_credentials"))\
                if dictionary.get("distribution_credentials") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(member,
                   distribution_credentials,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _member=self.member
        _distribution_credentials=self.distribution_credentials
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member={_member!r}, "
            f"distribution_credentials={_distribution_credentials!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _member=self.member
        _distribution_credentials=self.distribution_credentials
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member={_member!s}, "
            f"distribution_credentials={_distribution_credentials!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
