"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.list_models_v_1_response_tts_models_metadata import (
    ListModelsV1ResponseTtsModelsMetadata,
)


class ListModelsV1ResponseTtsModels(object):
    """Implementation of the 'ListModelsV1ResponseTtsModels' model.

    Attributes:
        name (str): The model property of type str.
        canonical_name (str): The model property of type str.
        architecture (str): The model property of type str.
        languages (List[str]): The model property of type List[str].
        version (str): The model property of type str.
        uuid (uuid|str): The model property of type uuid|str.
        metadata (ListModelsV1ResponseTtsModelsMetadata): The model property of type
            ListModelsV1ResponseTtsModelsMetadata.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "canonical_name": "canonical_name",
        "architecture": "architecture",
        "languages": "languages",
        "version": "version",
        "uuid": "uuid",
        "metadata": "metadata",
    }

    _optionals = [
        "name",
        "canonical_name",
        "architecture",
        "languages",
        "version",
        "uuid",
        "metadata",
    ]

    def __init__(
        self,
        name=APIHelper.SKIP,
        canonical_name=APIHelper.SKIP,
        architecture=APIHelper.SKIP,
        languages=APIHelper.SKIP,
        version=APIHelper.SKIP,
        uuid=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListModelsV1ResponseTtsModels instance."""
        # Initialize members of the class
        if name is not APIHelper.SKIP:
            self.name = name
        if canonical_name is not APIHelper.SKIP:
            self.canonical_name = canonical_name
        if architecture is not APIHelper.SKIP:
            self.architecture = architecture
        if languages is not APIHelper.SKIP:
            self.languages = languages
        if version is not APIHelper.SKIP:
            self.version = version
        if uuid is not APIHelper.SKIP:
            self.uuid = uuid
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        canonical_name =\
            dictionary.get("canonical_name")\
            if dictionary.get("canonical_name")\
                else APIHelper.SKIP
        architecture =\
            dictionary.get("architecture")\
            if dictionary.get("architecture")\
                else APIHelper.SKIP
        languages =\
            dictionary.get("languages")\
            if dictionary.get("languages")\
                else APIHelper.SKIP
        version =\
            dictionary.get("version")\
            if dictionary.get("version")\
                else APIHelper.SKIP
        uuid =\
            dictionary.get("uuid")\
            if dictionary.get("uuid")\
                else APIHelper.SKIP
        metadata =\
            ListModelsV1ResponseTtsModelsMetadata.from_dictionary(
                dictionary.get("metadata"))\
                if "metadata" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   canonical_name,
                   architecture,
                   languages,
                   version,
                   uuid,
                   metadata,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _canonical_name=(
            self.canonical_name
            if hasattr(self, "canonical_name")
            else None
        )
        _architecture=(
            self.architecture
            if hasattr(self, "architecture")
            else None
        )
        _languages=(
            self.languages
            if hasattr(self, "languages")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _uuid=(
            self.uuid
            if hasattr(self, "uuid")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"canonical_name={_canonical_name!r}, "
            f"architecture={_architecture!r}, "
            f"languages={_languages!r}, "
            f"version={_version!r}, "
            f"uuid={_uuid!r}, "
            f"metadata={_metadata!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _canonical_name=(
            self.canonical_name
            if hasattr(self, "canonical_name")
            else None
        )
        _architecture=(
            self.architecture
            if hasattr(self, "architecture")
            else None
        )
        _languages=(
            self.languages
            if hasattr(self, "languages")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _uuid=(
            self.uuid
            if hasattr(self, "uuid")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"canonical_name={_canonical_name!s}, "
            f"architecture={_architecture!s}, "
            f"languages={_languages!s}, "
            f"version={_version!s}, "
            f"uuid={_uuid!s}, "
            f"metadata={_metadata!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
