"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.listen_v_1_response_metadata_intents_info import (
    ListenV1ResponseMetadataIntentsInfo,
)
from restapi.models.listen_v_1_response_metadata_sentiment_info import (
    ListenV1ResponseMetadataSentimentInfo,
)
from restapi.models.listen_v_1_response_metadata_summary_info import (
    ListenV1ResponseMetadataSummaryInfo,
)
from restapi.models.listen_v_1_response_metadata_topics_info import (
    ListenV1ResponseMetadataTopicsInfo,
)


class ListenV1ResponseMetadata(object):
    """Implementation of the 'ListenV1ResponseMetadata' model.

    Attributes:
        transaction_key (str): The model property of type str.
        request_id (uuid|str): The model property of type uuid|str.
        sha_256 (str): The model property of type str.
        created (datetime): The model property of type datetime.
        duration (float): The model property of type float.
        channels (int): The model property of type int.
        models (List[str]): The model property of type List[str].
        model_info (Any): The model property of type Any.
        summary_info (ListenV1ResponseMetadataSummaryInfo): The model property of
            type ListenV1ResponseMetadataSummaryInfo.
        sentiment_info (ListenV1ResponseMetadataSentimentInfo): The model property of
            type ListenV1ResponseMetadataSentimentInfo.
        topics_info (ListenV1ResponseMetadataTopicsInfo): The model property of type
            ListenV1ResponseMetadataTopicsInfo.
        intents_info (ListenV1ResponseMetadataIntentsInfo): The model property of
            type ListenV1ResponseMetadataIntentsInfo.
        tags (List[str]): The model property of type List[str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "request_id": "request_id",
        "sha_256": "sha256",
        "created": "created",
        "duration": "duration",
        "channels": "channels",
        "models": "models",
        "model_info": "model_info",
        "transaction_key": "transaction_key",
        "summary_info": "summary_info",
        "sentiment_info": "sentiment_info",
        "topics_info": "topics_info",
        "intents_info": "intents_info",
        "tags": "tags",
    }

    _optionals = [
        "transaction_key",
        "summary_info",
        "sentiment_info",
        "topics_info",
        "intents_info",
        "tags",
    ]

    def __init__(
        self,
        request_id=None,
        sha_256=None,
        created=None,
        duration=None,
        channels=None,
        models=None,
        model_info=None,
        transaction_key="deprecated",
        summary_info=APIHelper.SKIP,
        sentiment_info=APIHelper.SKIP,
        topics_info=APIHelper.SKIP,
        intents_info=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListenV1ResponseMetadata instance."""
        # Initialize members of the class
        self.transaction_key = transaction_key
        self.request_id = request_id
        self.sha_256 = sha_256
        self.created =\
             APIHelper.apply_datetime_converter(
            created, APIHelper.RFC3339DateTime)\
             if created else None
        self.duration = duration
        self.channels = channels
        self.models = models
        self.model_info = model_info
        if summary_info is not APIHelper.SKIP:
            self.summary_info = summary_info
        if sentiment_info is not APIHelper.SKIP:
            self.sentiment_info = sentiment_info
        if topics_info is not APIHelper.SKIP:
            self.topics_info = topics_info
        if intents_info is not APIHelper.SKIP:
            self.intents_info = intents_info
        if tags is not APIHelper.SKIP:
            self.tags = tags

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None
        sha_256 =\
            dictionary.get("sha256")\
            if dictionary.get("sha256")\
                else None
        created = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created")).datetime\
            if dictionary.get("created") else None
        duration =\
            dictionary.get("duration")\
            if dictionary.get("duration")\
                else None
        channels =\
            dictionary.get("channels")\
            if dictionary.get("channels")\
                else None
        models =\
            dictionary.get("models")\
            if dictionary.get("models")\
                else None
        model_info =\
            dictionary.get("model_info")\
            if dictionary.get("model_info")\
                else None
        transaction_key =\
            dictionary.get("transaction_key")\
            if dictionary.get("transaction_key")\
                else "deprecated"
        summary_info =\
            ListenV1ResponseMetadataSummaryInfo.from_dictionary(
                dictionary.get("summary_info"))\
                if "summary_info" in dictionary.keys()\
                else APIHelper.SKIP
        sentiment_info =\
            ListenV1ResponseMetadataSentimentInfo.from_dictionary(
                dictionary.get("sentiment_info"))\
                if "sentiment_info" in dictionary.keys()\
                else APIHelper.SKIP
        topics_info =\
            ListenV1ResponseMetadataTopicsInfo.from_dictionary(
                dictionary.get("topics_info"))\
                if "topics_info" in dictionary.keys()\
                else APIHelper.SKIP
        intents_info =\
            ListenV1ResponseMetadataIntentsInfo.from_dictionary(
                dictionary.get("intents_info"))\
                if "intents_info" in dictionary.keys()\
                else APIHelper.SKIP
        tags =\
            dictionary.get("tags")\
            if dictionary.get("tags")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(request_id,
                   sha_256,
                   created,
                   duration,
                   channels,
                   models,
                   model_info,
                   transaction_key,
                   summary_info,
                   sentiment_info,
                   topics_info,
                   intents_info,
                   tags,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.request_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.sha_256,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.created,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.duration,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.channels,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.models,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.model_info,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        Any,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("request_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("sha256"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("created"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("duration"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("channels"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("models"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("model_info"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    Any,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _transaction_key=(
            self.transaction_key
            if hasattr(self, "transaction_key")
            else None
        )
        _request_id=self.request_id
        _sha_256=self.sha_256
        _created=self.created
        _duration=self.duration
        _channels=self.channels
        _models=self.models
        _model_info=self.model_info
        _summary_info=(
            self.summary_info
            if hasattr(self, "summary_info")
            else None
        )
        _sentiment_info=(
            self.sentiment_info
            if hasattr(self, "sentiment_info")
            else None
        )
        _topics_info=(
            self.topics_info
            if hasattr(self, "topics_info")
            else None
        )
        _intents_info=(
            self.intents_info
            if hasattr(self, "intents_info")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"transaction_key={_transaction_key!r}, "
            f"request_id={_request_id!r}, "
            f"sha_256={_sha_256!r}, "
            f"created={_created!r}, "
            f"duration={_duration!r}, "
            f"channels={_channels!r}, "
            f"models={_models!r}, "
            f"model_info={_model_info!r}, "
            f"summary_info={_summary_info!r}, "
            f"sentiment_info={_sentiment_info!r}, "
            f"topics_info={_topics_info!r}, "
            f"intents_info={_intents_info!r}, "
            f"tags={_tags!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _transaction_key=(
            self.transaction_key
            if hasattr(self, "transaction_key")
            else None
        )
        _request_id=self.request_id
        _sha_256=self.sha_256
        _created=self.created
        _duration=self.duration
        _channels=self.channels
        _models=self.models
        _model_info=self.model_info
        _summary_info=(
            self.summary_info
            if hasattr(self, "summary_info")
            else None
        )
        _sentiment_info=(
            self.sentiment_info
            if hasattr(self, "sentiment_info")
            else None
        )
        _topics_info=(
            self.topics_info
            if hasattr(self, "topics_info")
            else None
        )
        _intents_info=(
            self.intents_info
            if hasattr(self, "intents_info")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"transaction_key={_transaction_key!s}, "
            f"request_id={_request_id!s}, "
            f"sha_256={_sha_256!s}, "
            f"created={_created!s}, "
            f"duration={_duration!s}, "
            f"channels={_channels!s}, "
            f"models={_models!s}, "
            f"model_info={_model_info!s}, "
            f"summary_info={_summary_info!s}, "
            f"sentiment_info={_sentiment_info!s}, "
            f"topics_info={_topics_info!s}, "
            f"intents_info={_intents_info!s}, "
            f"tags={_tags!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
