"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class ListModelsV1ResponseTtsModelsMetadata(object):
    """Implementation of the 'ListModelsV1ResponseTtsModelsMetadata' model.

    Attributes:
        accent (str): The model property of type str.
        age (str): The model property of type str.
        color (str): The model property of type str.
        image (str): The model property of type str.
        sample (str): The model property of type str.
        tags (List[str]): The model property of type List[str].
        use_cases (List[str]): The model property of type List[str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "accent": "accent",
        "age": "age",
        "color": "color",
        "image": "image",
        "sample": "sample",
        "tags": "tags",
        "use_cases": "use_cases",
    }

    _optionals = [
        "accent",
        "age",
        "color",
        "image",
        "sample",
        "tags",
        "use_cases",
    ]

    def __init__(
        self,
        accent=APIHelper.SKIP,
        age=APIHelper.SKIP,
        color=APIHelper.SKIP,
        image=APIHelper.SKIP,
        sample=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        use_cases=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListModelsV1ResponseTtsModelsMetadata instance."""
        # Initialize members of the class
        if accent is not APIHelper.SKIP:
            self.accent = accent
        if age is not APIHelper.SKIP:
            self.age = age
        if color is not APIHelper.SKIP:
            self.color = color
        if image is not APIHelper.SKIP:
            self.image = image
        if sample is not APIHelper.SKIP:
            self.sample = sample
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if use_cases is not APIHelper.SKIP:
            self.use_cases = use_cases

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        accent =\
            dictionary.get("accent")\
            if dictionary.get("accent")\
                else APIHelper.SKIP
        age =\
            dictionary.get("age")\
            if dictionary.get("age")\
                else APIHelper.SKIP
        color =\
            dictionary.get("color")\
            if dictionary.get("color")\
                else APIHelper.SKIP
        image =\
            dictionary.get("image")\
            if dictionary.get("image")\
                else APIHelper.SKIP
        sample =\
            dictionary.get("sample")\
            if dictionary.get("sample")\
                else APIHelper.SKIP
        tags =\
            dictionary.get("tags")\
            if dictionary.get("tags")\
                else APIHelper.SKIP
        use_cases =\
            dictionary.get("use_cases")\
            if dictionary.get("use_cases")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(accent,
                   age,
                   color,
                   image,
                   sample,
                   tags,
                   use_cases,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _accent=(
            self.accent
            if hasattr(self, "accent")
            else None
        )
        _age=(
            self.age
            if hasattr(self, "age")
            else None
        )
        _color=(
            self.color
            if hasattr(self, "color")
            else None
        )
        _image=(
            self.image
            if hasattr(self, "image")
            else None
        )
        _sample=(
            self.sample
            if hasattr(self, "sample")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _use_cases=(
            self.use_cases
            if hasattr(self, "use_cases")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"accent={_accent!r}, "
            f"age={_age!r}, "
            f"color={_color!r}, "
            f"image={_image!r}, "
            f"sample={_sample!r}, "
            f"tags={_tags!r}, "
            f"use_cases={_use_cases!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _accent=(
            self.accent
            if hasattr(self, "accent")
            else None
        )
        _age=(
            self.age
            if hasattr(self, "age")
            else None
        )
        _color=(
            self.color
            if hasattr(self, "color")
            else None
        )
        _image=(
            self.image
            if hasattr(self, "image")
            else None
        )
        _sample=(
            self.sample
            if hasattr(self, "sample")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _use_cases=(
            self.use_cases
            if hasattr(self, "use_cases")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"accent={_accent!s}, "
            f"age={_age!s}, "
            f"color={_color!s}, "
            f"image={_image!s}, "
            f"sample={_sample!s}, "
            f"tags={_tags!s}, "
            f"use_cases={_use_cases!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
