"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.list_project_balances_v_1_response_balances_items import (
    ListProjectBalancesV1ResponseBalancesItems,
)


class ListProjectBalancesV1Response(object):
    """Implementation of the 'ListProjectBalancesV1Response' model.

    Attributes:
        balances (List[ListProjectBalancesV1ResponseBalancesItems]): The model
            property of type List[ListProjectBalancesV1ResponseBalancesItems].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "balances": "balances",
    }

    _optionals = [
        "balances",
    ]

    def __init__(
        self,
        balances=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListProjectBalancesV1Response instance."""
        # Initialize members of the class
        if balances is not APIHelper.SKIP:
            self.balances = balances

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        balances = None
        if dictionary.get("balances") is not None:
            balances = [
                ListProjectBalancesV1ResponseBalancesItems.from_dictionary(x)
                    for x in dictionary.get("balances")
            ]
        else:
            balances = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(balances,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _balances=(
            self.balances
            if hasattr(self, "balances")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"balances={_balances!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _balances=(
            self.balances
            if hasattr(self, "balances")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"balances={_balances!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
