"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class ListProjectPurchasesV1ResponseOrdersItems(object):
    """Implementation of the 'ListProjectPurchasesV1ResponseOrdersItems' model.

    Attributes:
        order_id (uuid|str): The model property of type uuid|str.
        expiration (datetime): The model property of type datetime.
        created (datetime): The model property of type datetime.
        amount (float): The model property of type float.
        units (str): The model property of type str.
        order_type (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "order_id": "order_id",
        "expiration": "expiration",
        "created": "created",
        "amount": "amount",
        "units": "units",
        "order_type": "order_type",
    }

    _optionals = [
        "order_id",
        "expiration",
        "created",
        "amount",
        "units",
        "order_type",
    ]

    def __init__(
        self,
        order_id=APIHelper.SKIP,
        expiration=APIHelper.SKIP,
        created=APIHelper.SKIP,
        amount=APIHelper.SKIP,
        units=APIHelper.SKIP,
        order_type=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListProjectPurchasesV1ResponseOrdersItems instance."""
        # Initialize members of the class
        if order_id is not APIHelper.SKIP:
            self.order_id = order_id
        if expiration is not APIHelper.SKIP:
            self.expiration =\
                 APIHelper.apply_datetime_converter(
                expiration, APIHelper.RFC3339DateTime)\
                 if expiration else None
        if created is not APIHelper.SKIP:
            self.created =\
                 APIHelper.apply_datetime_converter(
                created, APIHelper.RFC3339DateTime)\
                 if created else None
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if units is not APIHelper.SKIP:
            self.units = units
        if order_type is not APIHelper.SKIP:
            self.order_type = order_type

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        order_id =\
            dictionary.get("order_id")\
            if dictionary.get("order_id")\
                else APIHelper.SKIP
        expiration = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("expiration")).datetime\
            if dictionary.get("expiration") else APIHelper.SKIP
        created = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created")).datetime\
            if dictionary.get("created") else APIHelper.SKIP
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else APIHelper.SKIP
        units =\
            dictionary.get("units")\
            if dictionary.get("units")\
                else APIHelper.SKIP
        order_type =\
            dictionary.get("order_type")\
            if dictionary.get("order_type")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(order_id,
                   expiration,
                   created,
                   amount,
                   units,
                   order_type,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _order_id=(
            self.order_id
            if hasattr(self, "order_id")
            else None
        )
        _expiration=(
            self.expiration
            if hasattr(self, "expiration")
            else None
        )
        _created=(
            self.created
            if hasattr(self, "created")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _units=(
            self.units
            if hasattr(self, "units")
            else None
        )
        _order_type=(
            self.order_type
            if hasattr(self, "order_type")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"order_id={_order_id!r}, "
            f"expiration={_expiration!r}, "
            f"created={_created!r}, "
            f"amount={_amount!r}, "
            f"units={_units!r}, "
            f"order_type={_order_type!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _order_id=(
            self.order_id
            if hasattr(self, "order_id")
            else None
        )
        _expiration=(
            self.expiration
            if hasattr(self, "expiration")
            else None
        )
        _created=(
            self.created
            if hasattr(self, "created")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _units=(
            self.units
            if hasattr(self, "units")
            else None
        )
        _order_type=(
            self.order_type
            if hasattr(self, "order_type")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"order_id={_order_id!s}, "
            f"expiration={_expiration!s}, "
            f"created={_created!s}, "
            f"amount={_amount!s}, "
            f"units={_units!s}, "
            f"order_type={_order_type!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
