"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.list_project_distribution_credentials_v_1_response_distribution_credentials_items import (  # noqa: E501
    ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems,
)


class ListProjectDistributionCredentialsV1Response(object):
    """Implementation of the 'ListProjectDistributionCredentialsV1Response' model.

    Attributes:
        distribution_credentials
            (List[ListProjectDistributionCredentialsV1ResponseDistributionCredentialsI
            tems]): Array of distribution credentials with associated member
            information
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "distribution_credentials": "distribution_credentials",
    }

    _optionals = [
        "distribution_credentials",
    ]

    def __init__(
        self,
        distribution_credentials=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListProjectDistributionCredentialsV1Response instance."""
        # Initialize members of the class
        if distribution_credentials is not APIHelper.SKIP:
            self.distribution_credentials = distribution_credentials

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        distribution_credentials = None
        if dictionary.get("distribution_credentials") is not None:
            distribution_credentials = [
                ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems.from_dictionary(x)
                    for x in dictionary.get("distribution_credentials")
            ]
        else:
            distribution_credentials = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(distribution_credentials,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _distribution_credentials=(
            self.distribution_credentials
            if hasattr(self, "distribution_credentials")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"distribution_credentials={_distribution_credentials!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _distribution_credentials=(
            self.distribution_credentials
            if hasattr(self, "distribution_credentials")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"distribution_credentials={_distribution_credentials!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
