"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.list_project_keys_v_1_response_api_keys_items_api_key import (
    ListProjectKeysV1ResponseApiKeysItemsApiKey,
)
from restapi.models.list_project_keys_v_1_response_api_keys_items_member import (
    ListProjectKeysV1ResponseApiKeysItemsMember,
)


class ListProjectKeysV1ResponseApiKeysItems(object):
    """Implementation of the 'ListProjectKeysV1ResponseApiKeysItems' model.

    Attributes:
        member (ListProjectKeysV1ResponseApiKeysItemsMember): The model property of
            type ListProjectKeysV1ResponseApiKeysItemsMember.
        api_key (ListProjectKeysV1ResponseApiKeysItemsApiKey): The model property of
            type ListProjectKeysV1ResponseApiKeysItemsApiKey.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "member": "member",
        "api_key": "api_key",
    }

    _optionals = [
        "member",
        "api_key",
    ]

    def __init__(
        self,
        member=APIHelper.SKIP,
        api_key=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListProjectKeysV1ResponseApiKeysItems instance."""
        # Initialize members of the class
        if member is not APIHelper.SKIP:
            self.member = member
        if api_key is not APIHelper.SKIP:
            self.api_key = api_key

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        member =\
            ListProjectKeysV1ResponseApiKeysItemsMember.from_dictionary(
                dictionary.get("member"))\
                if "member" in dictionary.keys()\
                else APIHelper.SKIP
        api_key =\
            ListProjectKeysV1ResponseApiKeysItemsApiKey.from_dictionary(
                dictionary.get("api_key"))\
                if "api_key" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(member,
                   api_key,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _member=(
            self.member
            if hasattr(self, "member")
            else None
        )
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member={_member!r}, "
            f"api_key={_api_key!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _member=(
            self.member
            if hasattr(self, "member")
            else None
        )
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member={_member!s}, "
            f"api_key={_api_key!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
