"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class ReadV1ResponseMetadataMetadataSummaryInfo(object):
    """Implementation of the 'ReadV1ResponseMetadataMetadataSummaryInfo' model.

    Attributes:
        model_uuid (uuid|str): The model property of type uuid|str.
        input_tokens (int): The model property of type int.
        output_tokens (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "model_uuid": "model_uuid",
        "input_tokens": "input_tokens",
        "output_tokens": "output_tokens",
    }

    _optionals = [
        "model_uuid",
        "input_tokens",
        "output_tokens",
    ]

    def __init__(
        self,
        model_uuid=APIHelper.SKIP,
        input_tokens=APIHelper.SKIP,
        output_tokens=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ReadV1ResponseMetadataMetadataSummaryInfo instance."""
        # Initialize members of the class
        if model_uuid is not APIHelper.SKIP:
            self.model_uuid = model_uuid
        if input_tokens is not APIHelper.SKIP:
            self.input_tokens = input_tokens
        if output_tokens is not APIHelper.SKIP:
            self.output_tokens = output_tokens

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        model_uuid =\
            dictionary.get("model_uuid")\
            if dictionary.get("model_uuid")\
                else APIHelper.SKIP
        input_tokens =\
            dictionary.get("input_tokens")\
            if dictionary.get("input_tokens")\
                else APIHelper.SKIP
        output_tokens =\
            dictionary.get("output_tokens")\
            if dictionary.get("output_tokens")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(model_uuid,
                   input_tokens,
                   output_tokens,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _model_uuid=(
            self.model_uuid
            if hasattr(self, "model_uuid")
            else None
        )
        _input_tokens=(
            self.input_tokens
            if hasattr(self, "input_tokens")
            else None
        )
        _output_tokens=(
            self.output_tokens
            if hasattr(self, "output_tokens")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"model_uuid={_model_uuid!r}, "
            f"input_tokens={_input_tokens!r}, "
            f"output_tokens={_output_tokens!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _model_uuid=(
            self.model_uuid
            if hasattr(self, "model_uuid")
            else None
        )
        _input_tokens=(
            self.input_tokens
            if hasattr(self, "input_tokens")
            else None
        )
        _output_tokens=(
            self.output_tokens
            if hasattr(self, "output_tokens")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"model_uuid={_model_uuid!s}, "
            f"input_tokens={_input_tokens!s}, "
            f"output_tokens={_output_tokens!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
