"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.read_v_1_response_metadata import (
    ReadV1ResponseMetadata,
)
from restapi.models.read_v_1_response_results import (
    ReadV1ResponseResults,
)


class ReadV1Response(object):
    """Implementation of the 'ReadV1Response' model.

    The standard text response

    Attributes:
        metadata (ReadV1ResponseMetadata): The model property of type
            ReadV1ResponseMetadata.
        results (ReadV1ResponseResults): The model property of type
            ReadV1ResponseResults.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "metadata": "metadata",
        "results": "results",
    }

    def __init__(
        self,
        metadata=None,
        results=None,
        additional_properties=None):
        """Initialize a ReadV1Response instance."""
        # Initialize members of the class
        self.metadata = metadata
        self.results = results

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        metadata =\
            ReadV1ResponseMetadata.from_dictionary(
                dictionary.get("metadata"))\
                if dictionary.get("metadata") else None
        results =\
            ReadV1ResponseResults.from_dictionary(
                dictionary.get("results"))\
                if dictionary.get("results") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(metadata,
                   results,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _metadata=self.metadata
        _results=self.results
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"metadata={_metadata!r}, "
            f"results={_results!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _metadata=self.metadata
        _results=self.results
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"metadata={_metadata!s}, "
            f"results={_results!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
