"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper
from restapi.models.shared_sentiments_average import (
    SharedSentimentsAverage,
)
from restapi.models.shared_sentiments_segments_items import (
    SharedSentimentsSegmentsItems,
)


class SharedSentiments(object):
    """Implementation of the 'SharedSentiments' model.

    Output whenever `sentiment=true` is used

    Attributes:
        segments (List[SharedSentimentsSegmentsItems]): The model property of type
            List[SharedSentimentsSegmentsItems].
        average (SharedSentimentsAverage): The model property of type
            SharedSentimentsAverage.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "segments": "segments",
        "average": "average",
    }

    _optionals = [
        "segments",
        "average",
    ]

    def __init__(
        self,
        segments=APIHelper.SKIP,
        average=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SharedSentiments instance."""
        # Initialize members of the class
        if segments is not APIHelper.SKIP:
            self.segments = segments
        if average is not APIHelper.SKIP:
            self.average = average

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        segments = None
        if dictionary.get("segments") is not None:
            segments = [
                SharedSentimentsSegmentsItems.from_dictionary(x)
                    for x in dictionary.get("segments")
            ]
        else:
            segments = APIHelper.SKIP
        average =\
            SharedSentimentsAverage.from_dictionary(
                dictionary.get("average"))\
                if "average" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(segments,
                   average,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _segments=(
            self.segments
            if hasattr(self, "segments")
            else None
        )
        _average=(
            self.average
            if hasattr(self, "average")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"segments={_segments!r}, "
            f"average={_average!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _segments=(
            self.segments
            if hasattr(self, "segments")
            else None
        )
        _average=(
            self.average
            if hasattr(self, "average")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"segments={_segments!s}, "
            f"average={_average!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
