"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from restapi.api_helper import APIHelper


class UpdateProjectMemberScopesV1Request(object):
    """Implementation of the 'UpdateProjectMemberScopesV1Request' model.

    Attributes:
        scope (str): A scope to update
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "scope": "scope",
    }

    def __init__(
        self,
        scope=None,
        additional_properties=None):
        """Initialize a UpdateProjectMemberScopesV1Request instance."""
        # Initialize members of the class
        self.scope = scope

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        scope =\
            dictionary.get("scope")\
            if dictionary.get("scope")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(scope,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _scope=self.scope
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"scope={_scope!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _scope=self.scope
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"scope={_scope!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
