"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class V1ProjectsProjectIdRequestsGetParametersMethod(object):
    """Implementation of the 'V1ProjectsProjectIdRequestsGetParametersMethod' enum.

    Method type for the request

    Attributes:
        SYNC: The enum member of type str.
        ASYNC: The enum member of type str.
        STREAMING: The enum member of type str.

    """

    SYNC = "sync"

    ENUM_ASYNC = "async"

    STREAMING = "streaming"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
