"""restapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class V1ListenPostParametersModel0(object):
    """Implementation of the 'V1ListenPostParametersModel0' enum.

    Our public models available to all accounts

    Attributes:
        NOVA3: The enum member of type str.
        NOVA3GENERAL: The enum member of type str.
        NOVA3MEDICAL: The enum member of type str.
        NOVA2: The enum member of type str.
        NOVA2GENERAL: The enum member of type str.
        NOVA2MEETING: The enum member of type str.
        NOVA2FINANCE: The enum member of type str.
        NOVA2CONVERSATIONALAI: The enum member of type str.
        NOVA2VOICEMAIL: The enum member of type str.
        NOVA2VIDEO: The enum member of type str.
        NOVA2MEDICAL: The enum member of type str.
        NOVA2DRIVETHRU: The enum member of type str.
        NOVA2AUTOMOTIVE: The enum member of type str.
        NOVA: The enum member of type str.
        NOVAGENERAL: The enum member of type str.
        NOVAPHONECALL: The enum member of type str.
        NOVAMEDICAL: The enum member of type str.
        ENHANCED: The enum member of type str.
        ENHANCEDGENERAL: The enum member of type str.
        ENHANCEDMEETING: The enum member of type str.
        ENHANCEDPHONECALL: The enum member of type str.
        ENHANCEDFINANCE: The enum member of type str.
        BASE: The enum member of type str.
        MEETING: The enum member of type str.
        PHONECALL: The enum member of type str.
        FINANCE: The enum member of type str.
        CONVERSATIONALAI: The enum member of type str.
        VOICEMAIL: The enum member of type str.
        VIDEO: The enum member of type str.

    """

    _all_values = ["nova-3", "nova-3-general", "nova-3-medical", "nova-2", "nova-2-general",
        "nova-2-meeting", "nova-2-finance", "nova-2-conversationalai",
        "nova-2-voicemail", "nova-2-video", "nova-2-medical", "nova-2-drivethru",
        "nova-2-automotive", "nova", "nova-general", "nova-phonecall", "nova-medical",
        "enhanced", "enhanced-general", "enhanced-meeting", "enhanced-phonecall",
        "enhanced-finance", "base", "meeting", "phonecall", "finance",
        "conversationalai", "voicemail", "video"]
    NOVA3 = "nova-3"

    NOVA3GENERAL = "nova-3-general"

    NOVA3MEDICAL = "nova-3-medical"

    NOVA2 = "nova-2"

    NOVA2GENERAL = "nova-2-general"

    NOVA2MEETING = "nova-2-meeting"

    NOVA2FINANCE = "nova-2-finance"

    NOVA2CONVERSATIONALAI = "nova-2-conversationalai"

    NOVA2VOICEMAIL = "nova-2-voicemail"

    NOVA2VIDEO = "nova-2-video"

    NOVA2MEDICAL = "nova-2-medical"

    NOVA2DRIVETHRU = "nova-2-drivethru"

    NOVA2AUTOMOTIVE = "nova-2-automotive"

    NOVA = "nova"

    NOVAGENERAL = "nova-general"

    NOVAPHONECALL = "nova-phonecall"

    NOVAMEDICAL = "nova-medical"

    ENHANCED = "enhanced"

    ENHANCEDGENERAL = "enhanced-general"

    ENHANCEDMEETING = "enhanced-meeting"

    ENHANCEDPHONECALL = "enhanced-phonecall"

    ENHANCEDFINANCE = "enhanced-finance"

    BASE = "base"

    MEETING = "meeting"

    PHONECALL = "phonecall"

    FINANCE = "finance"

    CONVERSATIONALAI = "conversationalai"

    VOICEMAIL = "voicemail"

    VIDEO = "video"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
