"""deepgram.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from deepgram.api_helper import APIHelper
from deepgram.apis.base_api import BaseApi
from deepgram.configuration import Server
from deepgram.exceptions.listen_v_1_response_error_exception import (
    ListenV1ResponseErrorException,
)
from deepgram.http.http_method_enum import HttpMethodEnum
from deepgram.utilities.union_type_lookup import (
    UnionTypeLookUp,
)


class ListenV1MediaApi(BaseApi):
    """A Controller to access Endpoints in the deepgram API."""

    def __init__(self, config):
        """Initialize ListenV1MediaApi object."""
        super(ListenV1MediaApi, self).__init__(config)

    def transcribe(self,
                   callback=None,
                   callback_method="POST",
                   extra=None,
                   sentiment=False,
                   summarize=None,
                   tag=None,
                   topics=False,
                   custom_topic=None,
                   custom_topic_mode="extended",
                   intents=False,
                   custom_intent=None,
                   custom_intent_mode="extended",
                   detect_entities=False,
                   detect_language=None,
                   diarize=False,
                   diarize_model=None,
                   dictation=False,
                   encoding=None,
                   filler_words=False,
                   keyterm=None,
                   keywords=None,
                   language="en",
                   measurements=False,
                   model=None,
                   multichannel=False,
                   numerals=False,
                   paragraphs=False,
                   profanity_filter=False,
                   punctuate=False,
                   redact=None,
                   replace=None,
                   search=None,
                   smart_format=False,
                   utterances=False,
                   utt_split=0.8,
                   version=None,
                   mip_opt_out=False,
                   body=None):
        """Perform a POST request to /v1/listen.

        Transcribe audio and video using Deepgram's speech-to-text REST API

        Args:
            callback (str, optional): URL to which we'll make the callback request
            callback_method (V1ListenPostParametersCallbackMethod, optional): HTTP
                method by which the callback request will be made
            extra (str | List[str] | None, optional): Arbitrary key-value pairs that
                are attached to the API response for usage in downstream processing
            sentiment (bool, optional): Recognizes the sentiment throughout a
                transcript or text
            summarize (V1ListenPostParametersSummarize0 | bool | None, optional):
                Summarize content. For Listen API, supports string version option.
                For Read API, accepts boolean only.
            tag (str | List[str] | None, optional): Label your requests for the
                purpose of identification during usage reporting
            topics (bool, optional): Detect topics throughout a transcript or text
            custom_topic (str | List[str] | None, optional): Custom topics you want
                the model to detect within your input audio or text if present Submit
                up to `100`.
            custom_topic_mode (V1ListenPostParametersCustomTopicMode, optional): Sets
                how the model will interpret strings submitted to the `custom_topic`
                param. When `strict`, the model will only return topics submitted
                using the `custom_topic` param. When `extended`, the model will
                return its own detected topics in addition to those submitted using
                the `custom_topic` param
            intents (bool, optional): Recognizes speaker intent throughout a
                transcript or text
            custom_intent (str | List[str] | None, optional): Custom intents you want
                the model to detect within your input audio if present
            custom_intent_mode (V1ListenPostParametersCustomTopicMode, optional):
                Sets how the model will interpret intents submitted to the
                `custom_intent` param. When `strict`, the model will only return
                intents submitted using the `custom_intent` param. When `extended`,
                the model will return its own detected intents in the `custom_intent`
                param.
            detect_entities (bool, optional): Identifies and extracts key entities
                from content in submitted audio
            detect_language (bool | List[str] | None, optional): Identifies the
                dominant language spoken in submitted audio
            diarize (bool, optional): Deprecated: use `diarize_model` instead.
                Recognize speaker changes. Each word in the transcript will be
                assigned a speaker number starting at 0.
            diarize_model (V1ListenPostParametersDiarizeModel, optional): Select and
                enable a specific diarization model version. Specifying this
                parameter enables diarization and selects the model — you do not need
                to also set the deprecated `diarize=true` parameter. For batch,
                supported values are `latest` (currently v2), `v1`, and `v2`. For
                streaming, supported values are `latest` (currently v1) and `v1`;
                `v2` returns a validation error on streaming requests.
            dictation (bool, optional): Dictation mode for controlling formatting
                with dictated speech
            encoding (V1ListenPostParametersEncoding, optional): Specify the expected
                encoding of your submitted audio
            filler_words (bool, optional): Filler Words can help transcribe
                interruptions in your audio, like "uh" and "um"
            keyterm (List[str], optional): Key term prompting improves recognition of
                specialized terminology and brands. Only compatible with Nova-3.
                `keyterm` accepts plain terms only. Unlike the legacy `keywords`
                feature, it does not support weights or intensifiers. Appending one
                (for example, `keyterm=term:0.15`) is not rejected—the weight is
                silently ignored and the entire value is treated as a literal
                keyterm.  To boost multiple separate keyterms, repeat the `keyterm`
                parameter (for example, `keyterm=term1&keyterm=term2`). To boost one
                multi-word phrase as a single keyterm, join the words with `%20` or
                `+` (for example, `keyterm=customer%20service`). Do not separate
                keyterms with commas, semicolons, or line breaks.
            keywords (str | List[str] | None, optional): Keywords can boost or
                suppress specialized terminology and brands
            language (str, optional): The [BCP-47 language
                tag](https://tools.ietf.org/html/bcp47) that hints at the primary
                spoken language. Depending on the Model and API endpoint you choose
                only certain languages are available
            measurements (bool, optional): Spoken measurements will be converted to
                their corresponding abbreviations
            model (V1ListenPostParametersModel0 | str | None, optional): AI model
                used to process submitted audio
            multichannel (bool, optional): Transcribe each audio channel independently
            numerals (bool, optional): Numerals converts numbers from written format
                to numerical format
            paragraphs (bool, optional): Splits audio into paragraphs to improve
                transcript readability
            profanity_filter (bool, optional): Profanity Filter looks for recognized
                profanity and converts it to the nearest recognized non-profane word
                or removes it from the transcript completely
            punctuate (bool, optional): Add punctuation and capitalization to the
                transcript
            redact (str | List[V1ListenPostParametersRedactSchemaOneOf1Items] | None,
                optional): Redaction removes sensitive information from your
                transcripts
            replace (str | List[str] | None, optional): Search for terms or phrases
                in submitted audio and replaces them
            search (str | List[str] | None, optional): Search for terms or phrases in
                submitted audio
            smart_format (bool, optional): Apply formatting to transcript output.
                When set to true, additional formatting will be applied to
                transcripts to improve readability
            utterances (bool, optional): Segments speech into meaningful semantic
                units
            utt_split (float, optional): Seconds to wait before detecting a pause
                between words in submitted audio
            version (V1ListenPostParametersVersion0 | str | None, optional): Version
                of an AI model to use
            mip_opt_out (bool, optional): Opts out requests from the Deepgram Model
                Improvement Program. Refer to our Docs for pricing impacts before
                setting this to true. https://dpgr.am/deepgram-mip
            body (ListenV1RequestUrl, optional): Transcribe an audio or video file

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Returns either
                transcription results, or a request_id when using a callback.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/listen")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .query_param(Parameter()
                .key("callback")
                .value(callback))
            .query_param(Parameter()
                .key("callback_method")
                .value(callback_method))
            .query_param(Parameter()
                .key("extra")
                .value(extra)
                .validator(lambda value: UnionTypeLookUp
                    .get("V1ListenPostParametersExtra").validate(value)))
            .query_param(Parameter()
                .key("sentiment")
                .value(sentiment))
            .query_param(Parameter()
                .key("summarize")
                .value(summarize)
                .validator(lambda value: UnionTypeLookUp
                    .get("V1ListenPostParametersSummarize").validate(value)))
            .query_param(Parameter()
                .key("tag")
                .value(tag)
                .validator(lambda value: UnionTypeLookUp
                    .get("V1ListenPostParametersTag").validate(value)))
            .query_param(Parameter()
                .key("topics")
                .value(topics))
            .query_param(Parameter()
                .key("custom_topic")
                .value(custom_topic)
                .validator(lambda value: UnionTypeLookUp
                    .get("V1ListenPostParametersCustomTopic").validate(value)))
            .query_param(Parameter()
                .key("custom_topic_mode")
                .value(custom_topic_mode))
            .query_param(Parameter()
                .key("intents")
                .value(intents))
            .query_param(Parameter()
                .key("custom_intent")
                .value(custom_intent)
                .validator(lambda value: UnionTypeLookUp
                    .get("V1ListenPostParametersCustomIntent").validate(value)))
            .query_param(Parameter()
                .key("custom_intent_mode")
                .value(custom_intent_mode))
            .query_param(Parameter()
                .key("detect_entities")
                .value(detect_entities))
            .query_param(Parameter()
                .key("detect_language")
                .value(detect_language)
                .validator(lambda value: UnionTypeLookUp
                    .get("V1ListenPostParametersDetectLanguage").validate(value)))
            .query_param(Parameter()
                .key("diarize")
                .value(diarize))
            .query_param(Parameter()
                .key("diarize_model")
                .value(diarize_model))
            .query_param(Parameter()
                .key("dictation")
                .value(dictation))
            .query_param(Parameter()
                .key("encoding")
                .value(encoding))
            .query_param(Parameter()
                .key("filler_words")
                .value(filler_words))
            .query_param(Parameter()
                .key("keyterm")
                .value(keyterm))
            .query_param(Parameter()
                .key("keywords")
                .value(keywords)
                .validator(lambda value: UnionTypeLookUp
                    .get("V1ListenPostParametersKeywords").validate(value)))
            .query_param(Parameter()
                .key("language")
                .value(language))
            .query_param(Parameter()
                .key("measurements")
                .value(measurements))
            .query_param(Parameter()
                .key("model")
                .value(model)
                .validator(lambda value: UnionTypeLookUp
                    .get("TranscribeModel").validate(value)))
            .query_param(Parameter()
                .key("multichannel")
                .value(multichannel))
            .query_param(Parameter()
                .key("numerals")
                .value(numerals))
            .query_param(Parameter()
                .key("paragraphs")
                .value(paragraphs))
            .query_param(Parameter()
                .key("profanity_filter")
                .value(profanity_filter))
            .query_param(Parameter()
                .key("punctuate")
                .value(punctuate))
            .query_param(Parameter()
                .key("redact")
                .value(redact)
                .validator(lambda value: UnionTypeLookUp
                    .get("TranscribeRedact").validate(value)))
            .query_param(Parameter()
                .key("replace")
                .value(replace)
                .validator(lambda value: UnionTypeLookUp
                    .get("V1ListenPostParametersReplace").validate(value)))
            .query_param(Parameter()
                .key("search")
                .value(search)
                .validator(lambda value: UnionTypeLookUp
                    .get("V1ListenPostParametersSearch").validate(value)))
            .query_param(Parameter()
                .key("smart_format")
                .value(smart_format))
            .query_param(Parameter()
                .key("utterances")
                .value(utterances))
            .query_param(Parameter()
                .key("utt_split")
                .value(utt_split))
            .query_param(Parameter()
                .key("version")
                .value(version)
                .validator(lambda value: UnionTypeLookUp
                    .get("TranscribeVersion").validate(value)))
            .query_param(Parameter()
                .key("mip_opt_out")
                .value(mip_opt_out))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("ApiKeyAuth")),
        ).response(
            ResponseHandler()
            .deserializer(lambda value: APIHelper.deserialize_union_type(
                 UnionTypeLookUp
                 .get("listen_v1_media_transcribe_Response_200"), value))
            .is_api_response(True)
            .local_error("400", "Invalid Request", ListenV1ResponseErrorException),
        ).execute()
