from enum import Enum
from typing import Annotated, TypeAlias

from ...core import open_enum_validator


class V1SpeakPostParametersModel(str, Enum):
    AURA_ANGUS_EN = "aura-angus-en"
    AURA_ARCAS_EN = "aura-arcas-en"
    AURA_ASTERIA_EN = "aura-asteria-en"
    AURA_ATHENA_EN = "aura-athena-en"
    AURA_HELIOS_EN = "aura-helios-en"
    AURA_HERA_EN = "aura-hera-en"
    AURA_LUNA_EN = "aura-luna-en"
    AURA_ORION_EN = "aura-orion-en"
    AURA_ORPHEUS_EN = "aura-orpheus-en"
    AURA_PERSEUS_EN = "aura-perseus-en"
    AURA_STELLA_EN = "aura-stella-en"
    AURA_ZEUS_EN = "aura-zeus-en"
    AURA_2_AMALTHEA_EN = "aura-2-amalthea-en"
    AURA_2_ANDROMEDA_EN = "aura-2-andromeda-en"
    AURA_2_APOLLO_EN = "aura-2-apollo-en"
    AURA_2_ARCAS_EN = "aura-2-arcas-en"
    AURA_2_ARIES_EN = "aura-2-aries-en"
    AURA_2_ASTERIA_EN = "aura-2-asteria-en"
    AURA_2_ATHENA_EN = "aura-2-athena-en"
    AURA_2_ATLAS_EN = "aura-2-atlas-en"
    AURA_2_AURORA_EN = "aura-2-aurora-en"
    AURA_2_CALLISTA_EN = "aura-2-callista-en"
    AURA_2_CORA_EN = "aura-2-cora-en"
    AURA_2_CORDELIA_EN = "aura-2-cordelia-en"
    AURA_2_DELIA_EN = "aura-2-delia-en"
    AURA_2_DRACO_EN = "aura-2-draco-en"
    AURA_2_ELECTRA_EN = "aura-2-electra-en"
    AURA_2_HARMONIA_EN = "aura-2-harmonia-en"
    AURA_2_HELENA_EN = "aura-2-helena-en"
    AURA_2_HERA_EN = "aura-2-hera-en"
    AURA_2_HERMES_EN = "aura-2-hermes-en"
    AURA_2_HYPERION_EN = "aura-2-hyperion-en"
    AURA_2_IRIS_EN = "aura-2-iris-en"
    AURA_2_JANUS_EN = "aura-2-janus-en"
    AURA_2_JUNO_EN = "aura-2-juno-en"
    AURA_2_JUPITER_EN = "aura-2-jupiter-en"
    AURA_2_LUNA_EN = "aura-2-luna-en"
    AURA_2_MARS_EN = "aura-2-mars-en"
    AURA_2_MINERVA_EN = "aura-2-minerva-en"
    AURA_2_NEPTUNE_EN = "aura-2-neptune-en"
    AURA_2_ODYSSEUS_EN = "aura-2-odysseus-en"
    AURA_2_OPHELIA_EN = "aura-2-ophelia-en"
    AURA_2_ORION_EN = "aura-2-orion-en"
    AURA_2_ORPHEUS_EN = "aura-2-orpheus-en"
    AURA_2_PANDORA_EN = "aura-2-pandora-en"
    AURA_2_PHOEBE_EN = "aura-2-phoebe-en"
    AURA_2_PLUTO_EN = "aura-2-pluto-en"
    AURA_2_SATURN_EN = "aura-2-saturn-en"
    AURA_2_SELENE_EN = "aura-2-selene-en"
    AURA_2_THALIA_EN = "aura-2-thalia-en"
    AURA_2_THEIA_EN = "aura-2-theia-en"
    AURA_2_VESTA_EN = "aura-2-vesta-en"
    AURA_2_ZEUS_EN = "aura-2-zeus-en"
    AURA_2_AGUSTINA_ES = "aura-2-agustina-es"
    AURA_2_ALVARO_ES = "aura-2-alvaro-es"
    AURA_2_ANTONIA_ES = "aura-2-antonia-es"
    AURA_2_AQUILA_ES = "aura-2-aquila-es"
    AURA_2_CARINA_ES = "aura-2-carina-es"
    AURA_2_CELESTE_ES = "aura-2-celeste-es"
    AURA_2_DIANA_ES = "aura-2-diana-es"
    AURA_2_ESTRELLA_ES = "aura-2-estrella-es"
    AURA_2_GLORIA_ES = "aura-2-gloria-es"
    AURA_2_JAVIER_ES = "aura-2-javier-es"
    AURA_2_LUCIANO_ES = "aura-2-luciano-es"
    AURA_2_NESTOR_ES = "aura-2-nestor-es"
    AURA_2_OLIVIA_ES = "aura-2-olivia-es"
    AURA_2_SELENA_ES = "aura-2-selena-es"
    AURA_2_SILVIA_ES = "aura-2-silvia-es"
    AURA_2_SIRIO_ES = "aura-2-sirio-es"
    AURA_2_VALERIO_ES = "aura-2-valerio-es"
    AURA_2_AURELIA_DE = "aura-2-aurelia-de"
    AURA_2_ELARA_DE = "aura-2-elara-de"
    AURA_2_FABIAN_DE = "aura-2-fabian-de"
    AURA_2_JULIUS_DE = "aura-2-julius-de"
    AURA_2_KARA_DE = "aura-2-kara-de"
    AURA_2_LARA_DE = "aura-2-lara-de"
    AURA_2_VIKTORIA_DE = "aura-2-viktoria-de"
    AURA_2_BEATRIX_NL = "aura-2-beatrix-nl"
    AURA_2_CORNELIA_NL = "aura-2-cornelia-nl"
    AURA_2_DAPHNE_NL = "aura-2-daphne-nl"
    AURA_2_HESTIA_NL = "aura-2-hestia-nl"
    AURA_2_LARS_NL = "aura-2-lars-nl"
    AURA_2_LEDA_NL = "aura-2-leda-nl"
    AURA_2_RHEA_NL = "aura-2-rhea-nl"
    AURA_2_ROMAN_NL = "aura-2-roman-nl"
    AURA_2_SANDER_NL = "aura-2-sander-nl"
    AURA_2_AGATHE_FR = "aura-2-agathe-fr"
    AURA_2_HECTOR_FR = "aura-2-hector-fr"
    AURA_2_CESARE_IT = "aura-2-cesare-it"
    AURA_2_CINZIA_IT = "aura-2-cinzia-it"
    AURA_2_DEMETRA_IT = "aura-2-demetra-it"
    AURA_2_DIONISIO_IT = "aura-2-dionisio-it"
    AURA_2_ELIO_IT = "aura-2-elio-it"
    AURA_2_FLAVIO_IT = "aura-2-flavio-it"
    AURA_2_LIVIA_IT = "aura-2-livia-it"
    AURA_2_MAIA_IT = "aura-2-maia-it"
    AURA_2_MELIA_IT = "aura-2-melia-it"
    AURA_2_PERSEO_IT = "aura-2-perseo-it"
    AURA_2_AMA_JA = "aura-2-ama-ja"
    AURA_2_EBISU_JA = "aura-2-ebisu-ja"
    AURA_2_FUJIN_JA = "aura-2-fujin-ja"
    AURA_2_IZANAMI_JA = "aura-2-izanami-ja"
    AURA_2_UZUME_JA = "aura-2-uzume-ja"

    __str__ = str.__str__


V1SpeakPostParametersModelOrStr: TypeAlias = Annotated[
    V1SpeakPostParametersModel | str, open_enum_validator(V1SpeakPostParametersModel)
]
